import{describe,expect,it}from"vitest";import{analyzeDeterministicContinuity,type StoryEvent}from"@/lib/story-intelligence";
const event=(value:Partial<StoryEvent>&Pick<StoryEvent,"id"|"kind"|"entityId">):StoryEvent=>({sceneId:`scene-${value.id}`,position:1,value:"",label:value.id,...value});
describe("deterministic story intelligence",()=>{
it("cites knowledge used before discovery",()=>{const result=analyzeDeterministicContinuity([event({id:"use",kind:"KNOWLEDGE",entityId:"secret",subjectId:"lena",value:"USES"})]);expect(result[0]).toMatchObject({rule:"knowledge-before-discovery",severity:"HIGH",source:{recordId:"use"}})});
it("allows knowledge after a cited discovery",()=>{const result=analyzeDeterministicContinuity([event({id:"learn",kind:"KNOWLEDGE",entityId:"secret",subjectId:"lena",value:"LEARNS",position:1}),event({id:"use",kind:"KNOWLEDGE",entityId:"secret",subjectId:"lena",value:"USES",position:2})]);expect(result).toHaveLength(0)});
it("detects two simultaneous locations",()=>{const result=analyzeDeterministicContinuity([event({id:"a",kind:"LOCATION",entityId:"lena",value:"museum",position:2}),event({id:"b",kind:"LOCATION",entityId:"lena",value:"station",position:2})]);expect(result[0].rule).toBe("conflicting-location");expect(result[0].conflict?.recordId).toBe("a")});
it("detects object use by someone other than the latest holder",()=>{const result=analyzeDeterministicContinuity([event({id:"hold",kind:"OWNERSHIP",entityId:"key",subjectId:"lena",value:"HOLDS"}),event({id:"use",kind:"OWNERSHIP",entityId:"key",subjectId:"tomas",value:"USES",position:2})]);expect(result[0].rule).toBe("conflicting-object-ownership")});
it("detects state changes after death",()=>{const result=analyzeDeterministicContinuity([event({id:"death",kind:"DEATH",entityId:"mara",position:2}),event({id:"state",kind:"STATE",entityId:"mara",position:3})]);expect(result[0].category).toBe("LIFE_STATE")});
it("detects payoff without setup",()=>{const result=analyzeDeterministicContinuity([event({id:"payoff",kind:"PROMISE_PAYOFF",entityId:"open-gallery"})]);expect(result[0].rule).toBe("payoff-before-setup")});
it("detects missing translation segments",()=>{const result=analyzeDeterministicContinuity([event({id:"segment",kind:"TRANSLATION",entityId:"line-4",value:"MISSING"})]);expect(result[0].severity).toBe("MEDIUM")});
it("detects optimistic state conflicts",()=>{const result=analyzeDeterministicContinuity([event({id:"v1",kind:"STATE",entityId:"key",position:1}),event({id:"v2",kind:"STATE",entityId:"key",position:2,referenceId:"stale"})]);expect(result[0].rule).toBe("invalid-state-transition")});
});
