"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- compact toggle callback is intentionally expression-driven. */
import "@xyflow/react/dist/style.css";
import { memo, useMemo, useState } from "react";
import { Background, Controls, Handle, Position, ReactFlow, type Edge, type Node, type NodeProps } from "@xyflow/react";
import { Box, CircleHelp, MapPin, UserRound } from "lucide-react";
import type { CanvasScene, StoryEntity } from "@/lib/story-canvas/types";
import { fallbackWorldLayout } from "@/lib/storyworld/world-layout";
import styles from "./styles/WorldWorkspace.module.css";
type Data={label:string;type:"scene"|"person"|"place"|"object"|"question"|"event"|"faction";detail:string;meta:string;sourceSceneId?:string};
const icons={scene:MapPin,person:UserRound,place:MapPin,object:Box,question:CircleHelp,event:MapPin,faction:UserRound};
const WorldNode=memo(function WorldNode({data}:NodeProps<Node<Data>>){const Icon=icons[data.type];return <article className={`${styles.node} ${styles[data.type]}`} aria-label={`${data.type}: ${data.label}. ${data.detail}`}><Handle type="target" position={Position.Left}/><Icon/><span><small>{data.type}</small><strong>{data.label}</strong><em>{data.detail}</em><b>{data.meta}</b></span><Handle type="source" position={Position.Right}/></article>});
const nodeTypes={world:WorldNode};
const groups={Story:new Set(["scene","event"]),People:new Set(["person"]),Places:new Set(["place"]),Objects:new Set(["object"]),Questions:new Set(["question"]),Factions:new Set(["faction"])};
function graph(scenes:CanvasScene[],entities:StoryEntity[]){const raw:Node<Data>[]=[...scenes.map((scene,index)=>({id:`scene:${scene.id}`,type:"world",position:{x:0,y:0},data:{label:scene.title,type:"scene" as const,detail:`Chapter ${Math.floor(index/3)+1}`,meta:index===0?"Current story point":`${scene.wordCount} words`,sourceSceneId:scene.id}})),...entities.map(entity=>({id:`entity:${entity.id}`,type:"world",position:{x:0,y:0},data:{label:entity.name,type:entity.type,detail:entity.currentLocation??entity.currentHolder??entity.state??"Supported by the manuscript",meta:`${entity.appearances.length} appearances`,sourceSceneId:entity.appearances[0]}}))];const sceneIds=new Set(scenes.map(x=>x.id));const edges:Edge[]=entities.flatMap(entity=>entity.appearances.filter(id=>sceneIds.has(id)).map(id=>({id:`${entity.id}:${id}`,source:`entity:${entity.id}`,target:`scene:${id}`,type:"smoothstep"})));return{nodes:fallbackWorldLayout(raw),edges};}
export function StoryMap({scenes,entities,currentSceneId,onOpen,onSelect}:{scenes:CanvasScene[];entities:StoryEntity[];currentSceneId:string;onOpen:(id:string)=>void;onSelect?:(id:string)=>void}){const built=useMemo(()=>graph(scenes,entities),[scenes,entities]);const[layers,setLayers]=useState(new Set(Object.keys(groups)));const[selected,setSelected]=useState("");const visible=new Set(Object.entries(groups).filter(([key])=>layers.has(key)).flatMap(([,value])=>[...value]));const nodes=built.nodes.map(node=>({...node,className:selected&&selected!==node.id?styles.dim:""}));const nodeIds=new Set(nodes.filter(n=>visible.has(n.data.type)).map(n=>n.id));const edges=built.edges.filter(e=>nodeIds.has(e.source)&&nodeIds.has(e.target));return <main className={styles.workspace}><aside><small>WORLD LAYERS</small><h1>Story observatory</h1><p>See what the manuscript supports at this moment.</p>{Object.keys(groups).map(group=><label key={group}><input type="checkbox" checked={layers.has(group)} onChange={()=>setLayers(current=>{const next=new Set(current);next.has(group)?next.delete(group):next.add(group);return next;})}/><span>{group}</span></label>)}</aside><section className={styles.canvas} aria-label="Storyworld projection" data-layout-ready="true"><header><span>STORY POINT</span><strong>{scenes.findIndex(x=>x.id===currentSceneId)+1} / {scenes.length}</strong><small>{nodeIds.size} records · {edges.length} supported connections</small></header><ReactFlow nodes={nodes.filter(n=>nodeIds.has(n.id))} edges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.18}} minZoom={.2} maxZoom={1.8} onNodeClick={(_,node)=>{setSelected(node.id);if(node.id.startsWith("entity:"))onSelect?.(node.id.slice(7));}} onNodeDoubleClick={(_,node)=>{if(node.data.sourceSceneId)onOpen(node.data.sourceSceneId)}}><Background color="#303844" gap={28}/><Controls showInteractive={false}/></ReactFlow></section></main>}
