"use client";
import { useEffect, useState } from "react";
import type { EntityType, StoryChapter } from "@/lib/story-canvas/types";
import { StoryIcon } from "./StoryIcon";
type Kind = "part" | "chapter" | "scene" | EntityType | "note" | "research" | "import";
const items: Array<{ section: string; kind: Kind; label: string; icon: Parameters<typeof StoryIcon>[0]["name"] }> = [
  { section: "Structure", kind: "chapter", label: "Chapter", icon: "chapter" }, { section: "Structure", kind: "scene", label: "Scene", icon: "scene" }, { section: "Structure", kind: "part", label: "Part", icon: "library" },
  { section: "Story", kind: "person", label: "Person", icon: "person" }, { section: "Story", kind: "place", label: "Place", icon: "place" }, { section: "Story", kind: "object", label: "Object", icon: "object" }, { section: "Story", kind: "event", label: "Event", icon: "event" }, { section: "Story", kind: "faction", label: "Faction", icon: "person" }, { section: "Story", kind: "question", label: "Story question", icon: "warning" },
  { section: "Material", kind: "note", label: "Note", icon: "docs" }, { section: "Material", kind: "research", label: "Research", icon: "search" }, { section: "Material", kind: "import", label: "Import document", icon: "drive" },
];
export function GlobalCreate({ currentChapter, chapters, onClose, onPart, onChapter, onScene, onEntity, onImport }: { currentChapter?: StoryChapter; chapters: StoryChapter[]; onClose: () => void; onPart: (title: string) => void; onChapter: (title: string) => void; onScene: (chapterId: string, title: string) => void; onEntity: (type: EntityType, name: string) => void; onImport: () => void }) {
  const [kind, setKind] = useState<Kind | null>(null); const [name, setName] = useState(""); const [chapterId, setChapterId] = useState(currentChapter?.id ?? chapters[0]?.id ?? "");
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, [onClose]);
  const submit = () => { const title = name.trim() || (kind === "chapter" ? "Untitled chapter" : kind === "scene" ? "Untitled scene" : kind === "part" ? "Untitled part" : "Untitled"); if (kind === "part") onPart(title); else if (kind === "chapter") onChapter(title); else if (kind === "scene") onScene(chapterId, title); else if (kind === "import") onImport(); else if (kind && ["person", "place", "object", "event", "faction", "question"].includes(kind)) onEntity(kind as EntityType, title); onClose(); };
  return <div className="canvas-backdrop create-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="create-dialog" role="dialog" aria-modal="true" aria-label="Create story material"><header><div><small>New in your story</small><h2>{kind ? `Create ${items.find((item) => item.kind === kind)?.label.toLowerCase()}` : "Create"}</h2></div><button onClick={onClose} aria-label="Close Create"><StoryIcon name="close"/></button></header>{kind ? <form onSubmit={(event) => { event.preventDefault(); submit(); }}><label>{kind === "person" ? "Name" : kind === "place" ? "Place name" : kind === "object" ? "Object name" : kind === "event" ? "Event title" : "Title"}<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={kind === "chapter" ? "Untitled chapter" : kind === "scene" ? "Untitled scene" : "Start typing…"}/></label>{kind === "scene" && <label>Chapter<select value={chapterId} onChange={(event) => setChapterId(event.target.value)}>{chapters.filter((item) => item.status !== "archived").map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label>}<footer><button type="button" onClick={() => setKind(null)}>Back</button><button className="primary" type="submit">Create {items.find((item) => item.kind === kind)?.label.toLowerCase()}</button></footer></form> : <><div className="recent-create"><small>Suggested</small><button onClick={() => setKind("scene")}><StoryIcon name="scene"/><span>Add scene to <strong>{currentChapter?.title ?? "current chapter"}</strong></span><kbd>↵</kbd></button><button onClick={() => setKind("person")}><StoryIcon name="person"/><span>Add person to the current scene</span></button></div>{["Structure", "Story", "Material"].map((section) => <section className="create-section" key={section}><h3>{section}</h3><div>{items.filter((item) => item.section === section).map((item) => <button key={item.kind} onClick={() => item.kind === "import" ? onImport() : setKind(item.kind)}><StoryIcon name={item.icon}/><span>{item.label}</span></button>)}</div></section>)}</>}</section></div>;
}
