"use client";

import { useEffect, useRef, useState } from "react";
import type { CanvasMode, CanvasScene, ReviewFinding, StoryEntity } from "@/lib/story-canvas/types";

export function StoryLibrary({ entities, onClose, onOpen, onCreate }: { entities: StoryEntity[]; onClose: () => void; onOpen: (id: string) => void; onCreate: (name: string, type: StoryEntity["type"]) => void }) {
  const [tab, setTab] = useState("all"); const [query, setQuery] = useState(""); const [creating, setCreating] = useState<StoryEntity["type"] | null>(null); const [name, setName] = useState("");
  const visible = entities.filter((entity) => (tab === "all" || entity.type === tab) && entity.name.toLowerCase().includes(query.toLowerCase()));
  return <Dialog label="Story Library" onClose={onClose} className="library-dialog"><header><h2>Story Library</h2><button onClick={onClose}>×</button></header><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the story…" aria-label="Search Story Library"/><nav>{["all", "person", "place", "object", "event"].map((item) => <button key={item} aria-pressed={tab === item} onClick={() => setTab(item)}>{item === "all" ? "All" : `${item[0].toUpperCase()}${item.slice(1)}${item === "person" ? "e" : ""}s`}</button>)}</nav><div className="library-results">{visible.map((entity) => <button key={entity.id} onClick={() => onOpen(entity.id)}><span className={`entity-symbol ${entity.type}`}/><strong>{entity.name}</strong><small>{entity.type} · {entity.appearances.length} appearances</small><em>{entity.currentHolder ? `Held by ${entity.currentHolder}` : entity.currentLocation ?? entity.state ?? "Story record"}</em></button>)}</div><footer>{creating ? <form onSubmit={(event) => { event.preventDefault(); if (name.trim()) onCreate(name.trim(), creating); }}><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={`New ${creating} name`} aria-label={`New ${creating} name`}/><button type="submit">Create</button><button type="button" onClick={() => setCreating(null)}>Cancel</button></form> : <>{(["person", "place", "object", "event"] as const).map((type) => <button key={type} onClick={() => setCreating(type)}>＋ New {type}</button>)}</>}</footer></Dialog>;
}

export function ReviewDrawer({ findings, index, onClose, onNext, onDecide, onSource }: { findings: ReviewFinding[]; index: number; onClose: () => void; onNext: () => void; onDecide: (id: string, status: ReviewFinding["status"]) => void; onSource: (id: string) => void }) {
  const finding = findings[index % Math.max(1, findings.length)];
  useEffect(() => { const key = (event: KeyboardEvent) => { if (!finding) return; if (event.key.toLowerCase() === "a") onDecide(finding.id, "accepted"); if (event.key.toLowerCase() === "i") onDecide(finding.id, "intentional"); if (event.key.toLowerCase() === "d") onDecide(finding.id, "dismissed"); if (event.key === "ArrowRight") onNext(); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [finding, onDecide, onNext]);
  return <aside className="review-drawer" role="dialog" aria-modal="true" aria-label="Review story decisions"><header><span>Finding {findings.length ? index + 1 : 0} of {findings.length}</span><button onClick={onClose}>×</button></header>{finding ? <><blockquote>&ldquo;{finding.quote}&rdquo;</blockquote><h2>{finding.issue}</h2><p>{finding.reason}</p><button className="related-evidence" onClick={() => onSource(finding.sceneId)}><small>Relevant evidence</small>&ldquo;{finding.relatedQuote}&rdquo;</button><footer><button className="primary" onClick={() => onDecide(finding.id, "accepted")}>Accept correction <kbd>A</kbd></button><button onClick={() => onSource(finding.sceneId)}>Edit in scene <kbd>E</kbd></button><button onClick={() => onDecide(finding.id, "intentional")}>Mark intentional <kbd>I</kbd></button><button onClick={() => onDecide(finding.id, "dismissed")}>Dismiss <kbd>D</kbd></button><button onClick={onNext}>Next <kbd>→</kbd></button></footer></> : <p>All decisions reviewed.</p>}</aside>;
}

export function CommandPalette({ scenes, entities, onClose, onMode, onScene, onCommand }: { scenes: CanvasScene[]; entities: StoryEntity[]; onClose: () => void; onMode: (mode: CanvasMode) => void; onScene: (id: string) => void; onCommand: (command: string) => void }) {
  const [query, setQuery] = useState("");
  const commands = [{ label: "Switch to Write", run: () => onMode("write") }, { label: "Switch to Map", run: () => onMode("map") }, { label: "Switch to Trace", run: () => onMode("trace") }, ...["Create scene", "Create person", "Create place", "Create object", "Open Library", "Open Review", "Toggle Focus", "Reset demo"].map((label) => ({ label, run: () => onCommand(label) })), ...scenes.map((scene) => ({ label: scene.title, run: () => onScene(scene.id) })), ...entities.map((entity) => ({ label: entity.name, run: () => onCommand(`entity:${entity.id}`) }))];
  const visible = commands.filter((command) => command.label.toLowerCase().includes(query.toLowerCase())).slice(0, 12);
  return <Dialog label="Command palette" onClose={onClose} className="command-dialog"><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search scenes, people, places, objects, commands…"/><div>{visible.map((command) => <button key={command.label} onClick={() => { command.run(); onClose(); }}>{command.label}<span>↵</span></button>)}</div><footer>⌘K · Escape to close</footer></Dialog>;
}

export function SettingsPopover({ wordTarget, pulse, reducedMotion, textSize, onSetting, onReset, onClose }: { wordTarget: number; pulse: boolean; reducedMotion: boolean; textSize: number; onSetting: (key: "wordTarget" | "pulseEnabled" | "reducedMotion" | "textSize", value: number | boolean) => void; onReset: () => void; onClose: () => void }) {
  return <Dialog label="Demo settings" onClose={onClose} className="settings-dialog"><header><div><small>Demo session</small><h2>Story Canvas settings</h2></div><button onClick={onClose}>×</button></header><label>Daily word target<input type="number" value={wordTarget} onChange={(event) => onSetting("wordTarget", Number(event.target.value))}/></label><label><span>Story Pulse</span><input type="checkbox" checked={pulse} onChange={(event) => onSetting("pulseEnabled", event.target.checked)}/></label><label><span>Reduced motion</span><input type="checkbox" checked={reducedMotion} onChange={(event) => onSetting("reducedMotion", event.target.checked)}/></label><label>Manuscript text size<input type="range" min="17" max="25" value={textSize} onChange={(event) => onSetting("textSize", Number(event.target.value))}/></label><button className="reset-demo" onClick={onReset}>Reset demo</button></Dialog>;
}

function Dialog({ label, onClose, className, children }: { label: string; onClose: () => void; className: string; children: React.ReactNode }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [onClose]);
  return <div ref={ref} className="canvas-backdrop" onMouseDown={(event) => { if (event.target === ref.current) onClose(); }}><section className={className} role="dialog" aria-modal="true" aria-label={label}>{children}</section></div>;
}
