import "./globals.css";
import "./brand.css";
import "./editorial.css";
import "./publication.css";
import "./quality-pass.css";
import "./nav-quality.css";
import "./control-quality.css";
import "./refine.css";
import "./reliability.css";
import "./workspace.css";
import "./workspace-override.css";
import "./workspace-entities.css";
import "./studio-demo/studio-demo.css";
import "./studio-demo/story-font.css";
import "./studio-demo/mobile-overrides.css";
import "./studio-demo/commercial-v1.css";
import "./studio-demo/commercial-v1-fixes.css";
import "./storyworld.css";
import type { Metadata } from "next";
import { baseMetadata } from "@/lib/seo";
import { site } from "@/lib/site";
export const metadata:Metadata=baseMetadata();
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang={site.locale}><body>{children}</body></html>}
