"use client";
import Link from"next/link";import{useMemo,useState}from"react";
const entries=[
{title:"Build a middle that changes the story",topic:"Story structure",format:"Novel",anchor:"middle",summary:"Turn repeated attempts into movements that alter the kind of problem."},
{title:"Plan choices, not incidents",topic:"Story planning",format:"All formats",anchor:"turning-points",summary:"Make each major turn close one path and create a consequential new one."},
{title:"Build the character engine",topic:"Characters",format:"Novel",anchor:"character-engine",summary:"Connect goal, fear, mistaken belief, and need before adding plot machinery."},
{title:"Connect scenes through consequence",topic:"Scene writing",format:"All formats",anchor:"scene-sequence",summary:"Test what each scene passes into the next: a choice, wound, object, or obligation."},
{title:"Keep continuity cheap to change",topic:"Continuity",format:"All formats",anchor:"continuity",summary:"Trace knowledge, ownership, relationships, rules, and promises before the draft hardens."},
{title:"Adapt a plan to its writing form",topic:"Formats",format:"Screen · panels · games",anchor:"planning-by-format",summary:"Plan novels, screenplays, serial panels, and branching narrative in their own grammar."},
{title:"Design chapters around movement",topic:"Revision",format:"Novel",anchor:"chapter-design",summary:"Give each chapter a dominant pressure and an intended reading effect."},
{title:"Plan the next five scenes",topic:"Practical exercise",format:"All formats",anchor:"practical-exercise",summary:"A thirty-minute worksheet for turning pressure into a draftable sequence."},
];
export function EditorialLibrary(){const[query,setQuery]=useState("");const[topic,setTopic]=useState("All");const topics=["All",...new Set(entries.map(x=>x.topic))];const visible=useMemo(()=>entries.filter(x=>(topic==="All"||x.topic===topic)&&`${x.title} ${x.summary} ${x.format}`.toLowerCase().includes(query.toLowerCase())),[query,topic]);return <section className="editorial-library"><header><div><small>EXPLORE THE GUIDE</small><h2>Start with the problem in front of you.</h2></div><label>Search the library<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Scene, character, continuity…"/></label></header><nav aria-label="Editorial topics">{topics.map(item=><button aria-pressed={topic===item} onClick={()=>setTopic(item)} key={item}>{item}</button>)}</nav><div>{visible.map(entry=><Link href={`/blog/how-to-plan-a-novel#${entry.anchor}`} key={entry.anchor}><small>{entry.topic} · {entry.format}</small><h3>{entry.title}</h3><p>{entry.summary}</p><span>Read this chapter →</span></Link>)}</div>{!visible.length&&<p>No chapter matches those words. Try a broader craft question.</p>}</section>}
