"use client";
import{EditorContent,useEditor}from"@tiptap/react";import StarterKit from"@tiptap/starter-kit";import{useCallback,useEffect,useRef,useState}from"react";import{chooseRecoveryDraft,createDraft,deleteDraft,getDraft,listLocalVersions,putDraft,putLocalVersion,retryDelay,type LocalVersion,type ManuscriptDraft}from"@/lib/persistence/manuscript";
type Doc=Record<string,unknown>;type SaveState="local"|"syncing"|"cloud"|"offline"|"unsynced"|"conflict"|"failed"|"recovered";
const labels:Record<SaveState,string>={local:"Saved locally",syncing:"Saved locally · syncing",cloud:"Saved locally and to cloud",offline:"Saved locally · waiting to sync",unsynced:"Unsynced changes",conflict:"Conflict detected · local writing protected",failed:"Save failed · local writing protected",recovered:"Restored from recovery"};
export function ManuscriptEditor({projectId,sceneId,initialDocument,initialRevision}:{projectId:string;sceneId:string;initialDocument:Doc;initialRevision:number}){
 const revision=useRef(initialRevision),timer=useRef<ReturnType<typeof setTimeout>|null>(null),latest=useRef<ManuscriptDraft|null>(null),syncing=useRef(false);const[state,setState]=useState<SaveState>("cloud"),[versions,setVersions]=useState<LocalVersion[]>([]),[showVersions,setShowVersions]=useState(false);const editor=useEditor({immediatelyRender:false,extensions:[StarterKit],content:initialDocument,onUpdate:({editor:e})=>void journal(e.getJSON(),e.getText())});
 const refreshVersions=useCallback(()=>void listLocalVersions(projectId,sceneId).then(setVersions).catch(()=>setVersions([])),[projectId,sceneId]);
 const sync=useCallback(async(draft?:ManuscriptDraft)=>{const queued=draft??latest.current;if(!queued||syncing.current)return;if(!navigator.onLine){setState("offline");return}syncing.current=true;setState("syncing");try{const response=await fetch(`/api/projects/${projectId}/scenes/${sceneId}`,{method:"PUT",headers:{"content-type":"application/json","x-morrow-mutation-id":`${queued.key}:${queued.updatedAt}`},body:JSON.stringify({revision:revision.current,document:queued.document,text:queued.text})});const body=await response.json()as{revision?:number};if(response.status===409){await putDraft({...queued,syncState:"conflict"});setState("conflict");return}if(!response.ok)throw new Error(`Save failed (${response.status})`);revision.current=body.revision??revision.current+1;latest.current=null;await deleteDraft(projectId,sceneId);setState("cloud")}catch{const failed={...queued,syncState:"failed"as const,attempts:queued.attempts+1};latest.current=failed;await putDraft(failed).catch(()=>undefined);setState(navigator.onLine?"failed":"offline");timer.current=setTimeout(()=>void sync(failed),retryDelay(failed.attempts))}finally{syncing.current=false}},[projectId,sceneId]);
 async function journal(document:Doc,text:string){const draft=createDraft(projectId,sceneId,revision.current,document,text);latest.current=draft;try{await putDraft(draft);setState(navigator.onLine?"local":"offline")}catch{try{localStorage.setItem(`morrow-emergency:${draft.key}`,JSON.stringify(draft));setState("local")}catch{setState("failed")}}if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void sync(draft),900)}
 useEffect(()=>{if(!editor)return;void getDraft(projectId,sceneId).then(draft=>{const recovered=chooseRecoveryDraft(initialRevision,draft);if(recovered&&recovered.text!==editor.getText()){editor.commands.setContent(recovered.document,false);latest.current=recovered;setState("recovered")}}).catch(()=>{const raw=localStorage.getItem(`morrow-emergency:${projectId}:${sceneId}`);if(raw)try{const draft=JSON.parse(raw)as ManuscriptDraft;editor.commands.setContent(draft.document,false);latest.current=draft;setState("recovered")}catch{}});refreshVersions()},[editor,initialRevision,projectId,sceneId,refreshVersions]);
 useEffect(()=>{const online=()=>void sync();const offline=()=>latest.current&&setState("offline");addEventListener("online",online);addEventListener("offline",offline);return()=>{removeEventListener("online",online);removeEventListener("offline",offline);if(timer.current)clearTimeout(timer.current)}},[sync]);
 const snapshot=async(label:string)=>{if(!editor)return;await putLocalVersion({id:`${projectId}:${sceneId}:${Date.now()}`,key:`${projectId}:${sceneId}`,label,document:editor.getJSON(),text:editor.getText(),createdAt:new Date().toISOString(),baseRevision:revision.current});refreshVersions();setShowVersions(true)};
 const restore=async(version:LocalVersion)=>{if(!editor)return;await snapshot("Before version restore");editor.commands.setContent(version.document);setState("local")};
 const backup=()=>{if(!editor)return;const data=JSON.stringify({schemaVersion:1,projectId,sceneId,revision:revision.current,createdAt:new Date().toISOString(),document:editor.getJSON(),text:editor.getText()},null,2);const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([data],{type:"application/json"}));link.download=`morrow-${sceneId}-backup.json`;link.click();URL.revokeObjectURL(link.href)};
 if(!editor)return <div className="editor-loading">Loading protected editor…</div>;return <section className="manuscript"><div className="editor-toolbar"><button onClick={()=>editor.chain().focus().toggleBold().run()} aria-pressed={editor.isActive("bold")}>Bold</button><button onClick={()=>editor.chain().focus().toggleItalic().run()} aria-pressed={editor.isActive("italic")}>Italic</button><button onClick={()=>editor.chain().focus().toggleHeading({level:2}).run()}>Heading</button><button onClick={()=>void snapshot("Named version")}>Create version</button><button onClick={()=>{refreshVersions();setShowVersions(v=>!v)}} aria-expanded={showVersions}>Version history</button><button onClick={backup}>Download backup</button><span role="status" className={`save-${state}`}>{labels[state]}</span></div>{showVersions&&<aside className="version-history" aria-label="Version history"><header><b>Version history</b><button onClick={()=>setShowVersions(false)}>Close</button></header>{versions.length?versions.map(version=><article key={version.id}><span><b>{version.label}</b><small>{new Date(version.createdAt).toLocaleString()}</small></span><button onClick={()=>void restore(version)}>Restore</button></article>):<p>No local versions yet.</p>}</aside>}<EditorContent editor={editor}/><footer>{editor.getText().trim().split(/\s+/).filter(Boolean).length} words{(state==="failed"||state==="offline")&&<button onClick={()=>void sync()}>Retry sync</button>}</footer></section>}
