CREATE TYPE "WorkspaceRole" AS ENUM ('OWNER','WRITER','EDITOR','ARTIST','LETTERER','TRANSLATOR','PRODUCER','VIEWER');
CREATE TYPE "SeriesStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE "Genre" AS ENUM ('ACTION','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE');
CREATE TYPE "CanonStatus" AS ENUM ('DRAFT','APPROVED','DEPRECATED');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Profile" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL UNIQUE REFERENCES "User"("id") ON DELETE CASCADE, "displayName" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Workspace" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3));
CREATE TABLE "WorkspaceMember" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "Workspace"("id") ON DELETE CASCADE, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "role" "WorkspaceRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("workspaceId","userId"));
CREATE TABLE "Series" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "Workspace"("id") ON DELETE CASCADE, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "logline" TEXT NOT NULL, "synopsis" TEXT NOT NULL, "genre" "Genre" NOT NULL, "language" TEXT NOT NULL, "audience" TEXT NOT NULL, "status" "SeriesStatus" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), UNIQUE("workspaceId","slug"));
CREATE TABLE "Location" ("id" TEXT PRIMARY KEY, "seriesId" TEXT NOT NULL REFERENCES "Series"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "description" TEXT NOT NULL DEFAULT '', "canonStatus" "CanonStatus" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), UNIQUE("seriesId","name"));
CREATE TABLE "Character" ("id" TEXT PRIMARY KEY, "seriesId" TEXT NOT NULL REFERENCES "Series"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "aliases" TEXT NOT NULL DEFAULT '', "pronouns" TEXT NOT NULL DEFAULT '', "role" TEXT NOT NULL, "lifeStage" TEXT NOT NULL DEFAULT '', "appearance" TEXT NOT NULL DEFAULT '', "personality" TEXT NOT NULL DEFAULT '', "speechStyle" TEXT NOT NULL DEFAULT '', "motivations" TEXT NOT NULL DEFAULT '', "goals" TEXT NOT NULL DEFAULT '', "fears" TEXT NOT NULL DEFAULT '', "secrets" TEXT NOT NULL DEFAULT '', "canonStatus" "CanonStatus" NOT NULL DEFAULT 'DRAFT', "locationId" TEXT REFERENCES "Location"("id") ON DELETE SET NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3));
CREATE TABLE "WorldRule" ("id" TEXT PRIMARY KEY, "seriesId" TEXT NOT NULL REFERENCES "Series"("id") ON DELETE CASCADE, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "canonStatus" "CanonStatus" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3));
CREATE INDEX "WorkspaceMember_userId_idx" ON "WorkspaceMember"("userId");
CREATE INDEX "Series_workspaceId_deletedAt_idx" ON "Series"("workspaceId","deletedAt");
CREATE INDEX "Character_seriesId_deletedAt_idx" ON "Character"("seriesId","deletedAt");
CREATE INDEX "Location_seriesId_deletedAt_idx" ON "Location"("seriesId","deletedAt");
CREATE INDEX "WorldRule_seriesId_deletedAt_idx" ON "WorldRule"("seriesId","deletedAt");

