export type BlogSection={id:string;title:string;paragraphs:string[]};
export type BlogArticle={slug:string;title:string;excerpt:string;description:string;searchIntent:string;locale:"en"|"nl"|"de"|"es"|"pt";category:string;tags:string[];publishedAt:string;revisedAt:string;author:string;resource?:{title:string;description:string};sections:BlogSection[]};

export const articles:BlogArticle[]=[{
slug:"how-to-plan-a-novel",title:"How to plan a novel without planning the life out of it",excerpt:"A practical, flexible method for moving from a compelling premise to chapters and scenes—while leaving space for discovery.",description:"Learn how to plan a novel with a flexible story framework, character-driven turning points, scene cards, a workable middle, and a revision-ready outline.",searchIntent:"A novelist wants a complete but flexible process for planning a novel before or during a first draft.",locale:"en",category:"story-planning",tags:["novel-planning","outlining","scenes","characters"],publishedAt:"2026-07-15",revisedAt:"2026-07-15",author:"Morrow Editorial",resource:{title:"Flexible novel planning workbook",description:"A copyable set of premise, character pressure, turning-point, scene, and continuity prompts."},sections:[
{id:"what-planning-is-for",title:"Start with what planning is actually for",paragraphs:[
"A novel plan is not a contract with your future self. It is a way to make the next useful decision before the blank page asks you to make every decision at once. A good plan holds the pressure of the story: who wants what, why it matters now, what stands in the way, and how each major choice changes what remains possible. It should help you begin a scene with purpose. It should not prescribe every gesture, metaphor, or line of dialogue before you have heard the characters speak.",
"Writers often argue about planning as if the only options are a forty-page outline or complete improvisation. Most working processes sit between those extremes. You can decide the destination while discovering the road. You can plan the emotional turn of a chapter and improvise the conversation that creates it. You can outline the first act closely and leave the final act as a set of questions. The right amount of planning is the smallest amount that keeps you writing with confidence."
]},
{id:"premise",title:"Turn the idea into a premise with pressure",paragraphs:[
"An idea names something interesting. A premise turns that interest into sustained pressure. “A museum where paintings alter memories” is an idea. “A cautious curator must restore a forbidden portrait that changes one memory from her past each time she touches it” begins to create a novel. It gives us a person, an action, a cost, and a reason the story cannot remain still. The premise does not need to explain the ending. It needs to generate difficult choices.",
"Write the premise in one or two sentences, then test it with five questions. Who is forced to act? What do they want before the plot disrupts their life? What new desire or duty appears? What makes the obvious solution impossible? What becomes worse if they wait? If an answer is vague, resist adding lore. Strengthen the pressure instead. “The magic is ancient” rarely moves a story. “Every restoration erases a memory of her missing mother” immediately changes the protagonist’s choices."
]},
{id:"promise",title:"Name the experience you are promising the reader",paragraphs:[
"A premise describes the story situation; a narrative promise describes the experience. A locked-room mystery promises a fair trail of clues and a satisfying explanation. A romance promises that the central relationship will be emotionally decisive. A family saga promises change across years and generations. A quest fantasy promises movement through a widening world. Naming the promise helps you distinguish a fascinating detour from a scene that belongs in this particular book.",
"Complete this sentence: “Readers come to this novel to experience…” Be specific about the emotional and dramatic movement, not only the genre. Perhaps they come to watch two guarded sisters rebuild trust while investigating the memory-changing paintings their mother left behind. That sentence can guide proportion. If six chapters explore museum politics but the sisters barely meet, the plan may be serving the setting more than the promise. The answer is not necessarily to cut the politics; it may be to make the politics force the sisters into harder choices together."
]},
{id:"character-engine",title:"Build the character engine before the plot machinery",paragraphs:[
"Plots become difficult in the middle when events can happen but the protagonist has no compelling reason to choose one path over another. Before listing chapters, define four things about the central character: the concrete goal they pursue, the fear that shapes their decisions, the mistaken belief that keeps the fear in place, and the need they may not recognize. These do not have to form a neat therapeutic lesson. They create friction between what the character says they want and what their choices reveal.",
"For the curator, the goal might be to preserve the museum and prove she deserves her new position. Her fear is becoming unreliable like the mother who disappeared. Her mistaken belief is that control is the same as safety. Her unrecognized need is to trust another person with an incomplete truth. Now plot choices carry emotional meaning. Reporting the altered portrait protects the museum but risks her credibility. Hiding it protects her position but repeats her mother’s secrecy. Either choice moves both the external story and the internal one."
]},
{id:"opposition",title:"Design opposition that can change shape",paragraphs:[
"An antagonist is not simply someone who wants the protagonist to fail. Effective opposition applies pressure to the protagonist’s way of seeing the world. It can come from a person, an institution, a physical limit, a social expectation, or a conflict between two good obligations. A plan becomes richer when opposition evolves. The first obstacle blocks action. The next makes the cost personal. Later opposition may offer exactly what the protagonist wants at a price they can no longer accept.",
"List three forces working against the protagonist and give each one a legitimate desire. The museum director wants to protect the institution from scandal. The estranged sister wants the truth exposed even if the museum closes. The portrait seems to want restoration, but each repaired detail removes a memory that may contain evidence. Because these forces are not interchangeable, scenes can create different kinds of pressure. The director can win an argument while the sister remains morally right. The portrait can solve one mystery while making the family conflict harder."
]},
{id:"turning-points",title:"Plan choices, not just incidents",paragraphs:[
"A list of events can describe a busy novel that still feels passive. Turning points matter because a decision closes one path and opens another. Instead of writing “the portrait changes,” write “Lena hides the change from the director and asks her estranged sister for help.” The first version is an incident. The second creates a new alliance, a secret, and consequences. When planning major turns, record the choice, the reason it feels necessary, and the new problem created by making it.",
"Most novels benefit from a small number of structural anchors even when they do not follow a named beat sheet. Identify the disruption that makes ordinary life impossible, the commitment that carries the protagonist into unfamiliar consequences, a central turn that changes the meaning of the conflict, a crisis that removes the easy answer, and a final choice that demonstrates who the protagonist has become. Treat these as load-bearing questions, not page-number targets. Their exact position depends on the rhythm and length of the book."
]},
{id:"middle",title:"Build a middle that changes the story",paragraphs:[
"The middle often feels slow because the plan repeats the opening problem at a larger volume. The protagonist tries, fails, learns little, and tries again. Escalation is not only making the danger bigger. It changes the kind of problem. A useful middle widens understanding, narrows options, deepens relationships, and makes earlier assumptions impossible to maintain. By the midpoint, the protagonist should not be able to return to the first chapter with the same interpretation of events.",
"Plan the middle in movements rather than an undifferentiated chain of chapters. Movement one might test the obvious solution. Movement two reveals that success carries an unexpected cost. Movement three forces an alliance with someone the protagonist mistrusts. Movement four turns the investigation inward and exposes the protagonist’s complicity. Give each movement a question and an irreversible answer. “Can the restoration be stopped?” becomes “No; it has already changed the sister’s memory.” The answer creates the next, more personal question."
]},
{id:"subplots",title:"Make subplots press on the main story",paragraphs:[
"A subplot earns space by changing the meaning or difficulty of the main story. It may reveal another side of the theme, place emotional pressure on a decision, create a resource with a cost, or show the consequences of a different choice. A subplot that merely pauses the central story will eventually feel detachable, no matter how entertaining its scenes are. The solution is not to make every subplot about the same mystery. It is to make its changes matter when the main plot reaches a turning point.",
"For each subplot, write its desire, change, and point of contact. The sister relationship wants honesty, changes from avoidance to uneasy cooperation, and touches the main plot when Lena must decide whether to share the memory she is about to lose. A workplace subplot wants recognition, changes from rivalry to protection, and touches the plot when a colleague risks their job to preserve evidence. If you cannot name a point of contact, either create one or consider whether the material belongs in another book."
]},
{id:"chapters-scenes",title:"Move from turning points to chapters and scenes",paragraphs:[
"Chapters shape the reader’s experience of movement. Scenes create the changes that make movement real. Begin by grouping the major turns and subplot contacts into chapters that have a dominant question or pressure. Then plan the scenes needed to create, complicate, and answer that pressure. A chapter does not need one scene, and a scene does not have to end with a dramatic cliffhanger. It does need to alter knowledge, intention, relationship, position, or possibility.",
"Use a compact scene card: viewpoint, immediate want, obstacle, turn, outcome, and the question carried forward. For example: Lena wants the director to close the gallery; the director needs proof; Lena cannot show the changed photograph without revealing her own memory gap; her colleague mentions a visitor who remembers the portrait differently; Lena chooses to find him before involving the director. The outcome changes her plan and creates the next scene. Leave sensory detail and dialogue for drafting unless a line arrives that you do not want to lose."
]},
{id:"continuity",title:"Add continuity while the plan is still easy to change",paragraphs:[
"Planning is the cheapest moment to notice impossible timing, knowledge that arrives too early, an object in two places, or a promise without room for a payoff. You do not need an exhaustive encyclopedia. Track only details that constrain later choices: when characters learn important facts, where significant objects move, which relationships change, what rules cannot be broken without consequence, and which questions the story asks the reader to remember.",
"A simple pass after the scene plan is enough. Read only one thread at a time. Follow the silver key from introduction to final use. Follow what the sister knows about the mother. Follow the director’s trust in Lena. Follow each public explanation of the portrait’s origin. This is easier than rereading the entire outline while trying to remember every category at once. When you find a contradiction, decide whether to fix it, turn it into deliberate misdirection, or make the discovery part of the plot."
]},
{id:"discovery-space",title:"Leave deliberate space for discovery",paragraphs:[
"A flexible plan contains open doors. Mark the decisions that must happen for the ending to work, then mark the areas where you want drafting to teach you something. You might know that Lena and her sister enter the sealed gallery together but leave the exact route, obstacles, and conversation open. You might know the visitor lies without deciding which true detail gives him away. Open questions are not failures in the plan when they are chosen consciously.",
"Use confidence labels if they help: fixed, likely, possible, and open. Fixed material supports the promise or ending. Likely material currently creates the best route. Possible material is an alternative worth keeping nearby. Open material is meant to be discovered in prose. Revisit the labels after several chapters. A discovery in dialogue may turn a likely scene into the wrong scene. Update the plan rather than forcing the draft to obey an earlier guess."
]},
{id:"common-mistakes",title:"Common novel-planning mistakes",paragraphs:[
"The first mistake is planning information instead of drama: pages of history with no present choice. The second is confusing more events with greater escalation. The third is giving the protagonist a goal but no emotionally costly reason to pursue it. The fourth is treating every scene as equally important, which hides the turning points. The fifth is planning only the main plot and then attaching subplots wherever the pace seems slow. Each problem can be corrected by returning to desire, opposition, choice, and consequence.",
"Another common mistake is polishing the outline until drafting feels like transcription. If you already know every exchange, you may have spent the creative energy before reaching the manuscript. The opposite mistake is keeping the plan so abstract that it offers no help: “Lena investigates more” is not a scene. Aim for decisions with room inside them. Know why Lena enters the restoration lab, what makes the visit difficult, and how she leaves differently. Discover the room, rhythm, and precise emotional behavior in prose."
]},
{id:"step-by-step",title:"A practical planning sequence",paragraphs:[
"First, write the pressured premise and reader promise. Second, define the protagonist’s goal, fear, belief, and need. Third, create several kinds of opposition with their own legitimate desires. Fourth, identify five major choices from disruption to final decision. Fifth, build the middle in movements that answer increasingly personal questions. Sixth, connect each subplot to a major choice. Seventh, turn movements into chapters and scene cards. Eighth, trace knowledge, objects, relationships, rules, and promises for continuity. Ninth, label what is fixed and what remains open.",
"Do not complete the entire sequence if the first three steps are enough to begin. Some writers need a full map before drafting; others learn the story by writing twenty pages and returning to the plan with better questions. The sequence is circular. Drafting reveals character. Character changes turning points. A new turning point reshapes the middle. The plan should become more truthful as the manuscript grows, not remain impressive because it was written first."
]},
{id:"checklist",title:"Novel planning checklist",paragraphs:[
"Before drafting, check: Can you state who acts, what they want, what makes action costly, and why delay makes things worse? Can you name the experience promised to the reader? Does the protagonist face opposition that challenges their habitual way of solving problems? Are the major turns decisions with consequences rather than surprises alone? Does the middle change the kind of problem? Does each subplot touch a decisive moment? Can each planned scene alter something the next scene inherits?",
"Then check the practical details: Is important knowledge learned before it is used? Can characters physically reach the places the plan requires? Do significant objects have a clear holder and location? Does every deliberately raised question have space for an answer, escalation, or intentional non-resolution? Have you left open areas where drafting can surprise you? Finally, can you identify the very next scene and explain what its viewpoint character wants? If yes, the plan is ready to do its job."
]},
{id:"example",title:"Worked example: from premise to three scenes",paragraphs:[
"Premise: a cautious museum curator must restore a forbidden portrait that changes one memory from her past with every repaired detail. Promise: an intimate mystery about two sisters deciding whether truth is worth the memories it costs. Opening movement: establish Lena’s need for control, show the damaged portrait arriving without records, and let a small restoration change a photograph on her desk. Commitment: Lena hides the change from the director and calls the sister she has avoided for three years.",
"Scene one: Lena wants to catalogue the portrait before the opening; a sealed backing prevents inspection; she repairs a flake of paint; the childhood photograph changes; she locks the room. Scene two: she wants to prove the photograph was always that way; her colleague remembers the original; he notices her panic; she lies and takes the security footage. Scene three: she wants her sister to confirm the childhood memory; the sister refuses to help unless Lena reveals why she left; Lena admits the portrait bears their mother’s signature. Each outcome creates the next pressure."
]},
{id:"using-morrow",title:"How this planning method works inside Morrow",paragraphs:[
"In Morrow, the premise, reader promise, characters, chapters, scenes, and open questions live beside the manuscript rather than in separate files. A scene card can hold the immediate want, obstacle, turn, and outcome while the prose remains spacious. Reordering a scene keeps its character and continuity notes attached. The planning view is there when you need orientation and disappears when you return to writing.",
"The useful difference appears as the project grows. If Lena gives away the silver key in one scene, Morrow can quietly point to the later chapter where she still carries it. If a translated chapter uses a different name for the sealed gallery, the preferred term remains visible. These are prompts to review, not automatic edits. The author decides whether the detail changes, the moment is intentional, or the apparent contradiction becomes part of the mystery."
]},
{id:"faq",title:"Frequently asked questions",paragraphs:[
"How detailed should a novel outline be? Detailed enough that you can begin the next scene with a desire, obstacle, and likely change. Stop before the plan removes the discoveries you most enjoy making in prose. Can you plan after starting a draft? Yes. Many writers produce exploratory chapters, identify the real premise and character pressure, then build a plan around what the manuscript has taught them. Should every chapter end on a cliffhanger? No. It should create movement, which may be a question, decision, emotional turn, revelation, or change in possibility.",
"Do you need a named structure method? No. Three-act, four-act, five-act, sequence, beat-sheet, and scene-sequel approaches can offer useful questions, but none replaces understanding the particular promise and pressure of your novel. What if the draft leaves the plan? Ask whether the new direction better serves the reader promise and character choices. If it does, change the plan. How do you avoid overplanning? Keep dialogue, sensory discovery, and minor behavior open; plan consequences more firmly than expression."
]}
]}];

export const articleBySlug=new Map(articles.map(article=>[article.slug,article]));
export function readingMinutes(article:BlogArticle){const words=article.sections.flatMap(section=>section.paragraphs).join(" ").split(/\s+/).length;return Math.max(1,Math.ceil(words/220))}
export function articleWordCount(article:BlogArticle){return article.sections.flatMap(section=>section.paragraphs).join(" ").split(/\s+/).filter(Boolean).length}
