export type MarketingPage={slug:string;eyebrow:string;title:string;description:string;proof:string[];sections:{title:string;body:string}[]};
export const marketingPages:MarketingPage[]=[
{slug:"product",eyebrow:"ONE STORY SYSTEM",title:"From first premise to final manuscript.",description:"PanelForge connects planning, prose, continuity, revision, and export in one private project graph.",proof:["Structured story memory","Evidence-linked analysis","Writer-controlled canon"],sections:[{title:"One source of truth",body:"Characters, locations, rules, scenes, and prose remain connected instead of drifting across documents."},{title:"Built for long projects",body:"Partial loading, scoped search, versioned saves, and compact AI context keep large stories manageable."}]},
{slug:"writing",eyebrow:"PROFESSIONAL DRAFTING",title:"A writing room with the whole story nearby.",description:"Draft in a structured long-form editor while scene purpose, beats, and canon stay visible.",proof:["Rich-text manuscripts","Conflict-safe autosave","Private Markdown export"],sections:[{title:"Structure and prose together",body:"Move between chapters, scenes, beats, and manuscript text without rebuilding context."},{title:"Every save recoverable",body:"Optimistic revisions prevent stale overwrites and preserve attributable manuscript history."}]},
{slug:"planning",eyebrow:"NARRATIVE ARCHITECTURE",title:"Plans that remain connected to the draft.",description:"Turn premise, characters, locations, and world rules into scene-level decisions.",proof:["Project story bible","Ordered beats","Project-scoped search"],sections:[{title:"Make intent explicit",body:"Give each scene a purpose, conflict, stakes, and outcome before or during drafting."},{title:"Find evidence",body:"Search canon and prose inside the correct private project boundary."}]},
{slug:"continuity",eyebrow:"CITED STORY INTELLIGENCE",title:"Catch contradictions while they are still cheap to fix.",description:"Review a scene against the exact canon records that constrain it.",proof:["Cited source IDs","No silent edits","Accept or reject findings"],sections:[{title:"Grounded, not generic",body:"Analysis receives the selected scene, beats, characters, world rules, language, and narrative constraints."},{title:"Author remains final",body:"Suggestions persist separately and never become manuscript or canon automatically."}]},
{slug:"revision",eyebrow:"REVISION WITH EVIDENCE",title:"Turn feedback into deliberate story decisions.",description:"Connect every finding to a scene, source, assumption, and author decision.",proof:["Version history","Before/after foundation","Decision provenance"],sections:[{title:"Preserve the original",body:"Manuscript versions provide a reliable foundation for comparison and recovery."},{title:"Review the reasoning",body:"See context, assumptions, and risks before accepting a finding."}]},
{slug:"languages",eyebrow:"MULTILINGUAL BY DESIGN",title:"Write in your language—not through English.",description:"Keep interface preference separate from manuscript language and regional editorial convention.",proof:["English","Nederlands","Deutsch","Español","Português"],sections:[{title:"Regional precision",body:"Projects select variants such as en-GB, nl-BE, de-CH, es-MX, and pt-BR."},{title:"Stable multilingual canon",body:"Entities keep stable IDs across future translations instead of fragmenting into copies."}]},
{slug:"google",eyebrow:"GOOGLE WORKSPACE",title:"Bring the working system you already use.",description:"A consent-first integration architecture for Docs, Sheets, Drive, and Calendar.",proof:["Incremental scopes","Preview before import","No silent overwrite"],sections:[{title:"Connect deliberately",body:"Authentication and Workspace permissions remain separate, with visible scopes and revocation."},{title:"Preview every import",body:"Normalize headings or rows, show conflicts, and require confirmation before project changes."}]},
{slug:"pricing",eyebrow:"CONFIGURABLE PLANS",title:"Choose capacity around the way you write.",description:"Plan architecture supports projects, words, storage, AI, collaborators, exports, and translations. Commercial prices are not yet approved.",proof:["Monthly or annual architecture","Usage allowances","No browser-trusted pricing"],sections:[{title:"Transparent dimensions",body:"Compare product limits and capabilities without invented discounts or artificial urgency."},{title:"Billing boundaries",body:"Future checkout and webhooks will derive prices server-side and process events idempotently."}]},
{slug:"security",eyebrow:"PRIVATE BY DEFAULT",title:"Your manuscript is not a marketing asset.",description:"Project access, exports, saves, and AI context are authorized on the server.",proof:["Tenant isolation","Exportable projects","Scoped AI context"],sections:[{title:"Private project boundaries",body:"Workspace membership gates project reads and every sensitive mutation."},{title:"Controlled intelligence",body:"Only the smallest relevant context is sent for analysis; full prose is never product analytics."}]}
];
export const marketingBySlug=new Map(marketingPages.map(p=>[p.slug,p]));
export const pricingConfig={billingPeriods:["monthly","annual"] as const,currencies:["EUR","USD","GBP"] as const,plans:[{id:"writer",name:"Writer",description:"For focused individual projects",features:["Private projects","Rich-text drafting","Structured story bible","Markdown export"]},{id:"studio",name:"Studio",description:"For collaborative story development",features:["Everything in Writer","Collaboration architecture","Translation workflows","Expanded usage controls"]}]};
