import { brand } from "@/lib/site";

export type PageKind = "system" | "craft" | "intelligence" | "format" | "integration" | "language" | "trust" | "commercial";
export type MarketingPage = {
  slug: string; kind: PageKind; eyebrow: string; title: string; description: string;
  proof: string[]; interaction: { label: string; input: string; output: string };
  sections: { title: string; body: string }[]; links: string[];
};
const page=(slug:string,kind:PageKind,eyebrow:string,title:string,description:string,proof:string[],interaction:MarketingPage["interaction"],sections:MarketingPage["sections"],links:string[]):MarketingPage=>({slug,kind,eyebrow,title,description,proof,interaction,sections,links});
const evidence={label:"Trace the evidence",input:"Mara names the red key in Scene 12.",output:"Conflict: she first learns its purpose in Scene 14 · high severity · 2 sources"};
const graph={label:"Change the graph lens",input:"Knowledge → promises → relationships",output:"The same scene reveals different causal paths without changing canon."};
const format={label:"Switch the writing format",input:"Novel → screenplay → webtoon",output:"Structure adapts: chapter/scene → slugline/dialogue → episode/beat/panel."};
const language={label:"Compare editorial conventions",input:"en-US → de-DE → es-MX",output:"“I know.” → „Ich weiß es.“ → —Lo sé. Register and punctuation remain explicit."};
const google={label:"Preview an import",input:"The Glass Harbour · Google Doc",output:"19 scenes · 8 characters · 3 review questions · no records changed yet"};

export const marketingPages:MarketingPage[]=[
page("product","system","CONNECTED STORY SYSTEM",brand.promise,"A private workspace where prose, canon, time, knowledge, and consequences remain connected.",["Structured story memory","Evidence-linked findings","Writer-controlled canon"],graph,[{title:"One story, not twelve files",body:"Manuscript blocks and story entities share stable references, so a change can reveal its downstream impact."},{title:"Decisions stay attributable",body:"Suggestions remain proposals until the writer accepts, edits, rejects, or marks them intentional."}],["story-graph","writing","security"]),
page("writing","craft","PROFESSIONAL DRAFTING","Write with the whole story within reach.","A structured rich-text manuscript beside scene purpose, beats, canon, and cited editorial intelligence.",["TipTap editor","Versioned saves","Markdown export"],{label:"Inspect a scene",input:"Purpose · conflict · stakes · outcome",output:"The scene changes Mara’s belief, Ivo’s trust, and the key’s known location."},[{title:"Structure beside prose",body:"Draft without flattening chapters, scenes, beats, POV, tense, or scene intent into one document."},{title:"Safe revision foundation",body:"Optimistic revisions reject stale saves and preserve attributable manuscript versions."}],["planning","revision","formats"]),
page("planning","craft","NARRATIVE ARCHITECTURE","Plans that survive contact with the draft.","Connect premise, audience, characters, rules, events, threads, and promises to the scenes that use them.",["Story bible","Ordered beats","Project-scoped search"],graph,[{title:"Make intent visible",body:"Purpose, conflict, stakes, and outcome turn an outline into testable narrative intent."},{title:"Retrieve, do not invent",body:"Project search returns evidence inside the authorized story boundary and says when none exists."}],["characters","timeline","worldbuilding"]),
page("story-intelligence","intelligence","EVIDENCE, NOT ORACLES","Story intelligence that shows its work.","Every finding presents the current scene, conflicting source, severity, reasoning, and available author actions.",["Cited sources","Explicit uncertainty","No silent edits"],evidence,[{title:"Grounded operations",body:"Selected scope, retrieved canon, manuscript context, locale, and constraints define each analysis request."},{title:"Writer judgment remains final",body:"Accept, edit, reject, compare, create an alternate, or turn a finding into a revision task."}],["continuity","revision","story-graph"]),
page("story-graph","system","LIVING STORY MODEL","See the story as a system of causes.","Move between knowledge, relationships, objects, promises, time, and branches without losing the manuscript.",["Typed entities","Deterministic paths","Canon states"],graph,[{title:"Meaningful nodes",body:"Characters, scenes, facts, objects, rules, reveals, setups, and payoffs are different records—not decorative dots."},{title:"Impact before mutation",body:"A graph query can surface affected scenes and facts before the author confirms a canon change."}],["relationships","timeline","continuity"]),
page("characters","craft","CHARACTER SYSTEMS","Characters are changing states, not profile cards.","Track goals, fears, beliefs, secrets, knowledge, voice, relationships, and scene-level change.",["Knowledge ledger foundation","Aliases and voice","Canon status"],evidence,[{title:"Belief is not truth",body:"A character can confidently believe a false fact while the story graph preserves the underlying truth."},{title:"Change across scenes",body:"Relationship and emotional state belong to a timeline, not a timeless biography."}],["relationships","continuity","revision"]),
page("relationships","intelligence","RELATIONAL CONTINUITY","Track what changes between people.","Expose trust, leverage, intimacy, rivalry, and withheld knowledge across the scenes that alter them.",["Scene-linked states","Directional dynamics","Branch-aware foundation"],graph,[{title:"Direction matters",body:"Mara trusting Ivo is not the same record as Ivo trusting Mara."},{title:"Explain the turn",body:"Each relationship state can point back to the decision, revelation, or injury that caused it."}],["characters","story-graph","timeline"]),
page("worldbuilding","craft","WORLD RULES IN MOTION","Build worlds that constrain the plot.","Connect locations, factions, objects, rules, exceptions, and consequences to manuscript evidence.",["Canon states","Stable references","Scoped search"],graph,[{title:"Rules need consequences",body:"A rule becomes useful when scenes can cite it and violations can be surfaced for review."},{title:"Objects have histories",body:"Ownership, holder, location, condition, transfer, and symbolic meaning change over time."}],["timeline","characters","planning"]),
page("timeline","system","STORY TIME, MADE LEGIBLE","Separate event order from reveal order.","Track when something happens, when a character learns it, and when the reader is allowed to know.",["Event chronology","Knowledge chronology","Reveal chronology"],graph,[{title:"Three clocks",body:"Story truth, character belief, and audience knowledge often move on different timelines."},{title:"Find impossible sequences",body:"Inspect prerequisites and travel, possession, knowledge, and emotional state at a scene boundary."}],["continuity","story-graph","revision"]),
page("continuity","intelligence","CITED CONTINUITY","Catch contradictions while they are still cheap to fix.","Review scene claims against the exact canon and manuscript records that constrain them.",["Source references","Severity","Intentional exceptions"],evidence,[{title:"Explain the conflict",body:"A useful finding states what conflicts, where both claims occur, and why the mismatch matters."},{title:"Preserve deliberate ambiguity",body:"Mark intentional misdirection without deleting the evidence that triggered review."}],["story-intelligence","timeline","revision"]),
page("revision","intelligence","REVISION WITH CONSEQUENCES","Change one truth. See what else moves.","Turn findings into a prioritized plan with before/after context and affected story records.",["Version history","Revision tasks","Impact foundation"],evidence,[{title:"From diagnosis to work",body:"Developmental findings become explicit tasks rather than disappearing into a chat transcript."},{title:"Protect downstream meaning",body:"Review affected scenes, threads, facts, and translations before accepting a structural change."}],["story-intelligence","continuity","writing"]),
page("translation","language","VOICE ACROSS LANGUAGES","Translate the story, not only the words.","Keep stable canon while adapting punctuation, register, address, vocabulary, and character voice.",["Source-linked segments","Glossary foundation","Regional variants"],language,[{title:"Convention-aware",body:"Dialogue punctuation and address conventions belong to the target locale, not the source manuscript."},{title:"Decisions remain visible",body:"Store source, target, glossary choices, and unresolved questions as separate reviewable records."}],["languages","revision","google-sheets"]),
page("formats","format","FORMAT-AWARE WORKSPACES","One story system. Eight ways to write.","Choose novel, screenplay, TV, webtoon, manga, comic, game narrative, or story-universe structure.",["Adaptive terminology","Format-specific structure","Shared canon foundation"],format,[{title:"Structure changes",body:"The workspace adapts its hierarchy and planning fields rather than applying a cosmetic label."},{title:"Canon travels",body:"Characters, rules, timeline, and knowledge remain stable when a project spans multiple expressions."}],["novel-writing","screenwriting","webtoon-writing"]),
page("novel-writing","format","NOVEL WORKSPACE","Chapters, scenes, prose, POV, and word intent.","Plan long-form narrative while keeping scene change and character knowledge beside the manuscript.",["Chapter hierarchy","Scene purpose","POV and tense"],format,[{title:"Long-form focus",body:"Navigate only the relevant chapter and scene instead of loading an entire manuscript into the browser."},{title:"Prose stays primary",body:"Structure supports the writing; it does not turn a novel into a database form."}],["writing","planning","revision"]),
page("screenwriting","format","SCREENPLAY WORKSPACE","Write in scenes, action, cues, and dialogue.","A format-aware foundation for sluglines, action, character cues, dialogue, and scene review.",["Scene headings","Dialogue roles","Causal review"],format,[{title:"Screen structure",body:"Scene location, time, action, and character cues require different controls from prose chapters."},{title:"Honest scope",body:"The current foundation adapts concepts but does not yet claim industry-standard screenplay pagination."}],["tv-writing","characters","story-intelligence"]),
page("tv-writing","format","TV STORY ROOM","Season arcs meet episode causality.","Organize episodes, acts, A/B/C plots, character arcs, and season promises in a shared canon.",["Episode hierarchy","Plot lanes","Season arc foundation"],format,[{title:"Across episodes",body:"A promise made in episode two can remain visible when its payoff moves three drafts later."},{title:"Parallel plot pressure",body:"Track plot lanes as connected threads rather than color labels on isolated index cards."}],["screenwriting","story-graph","revision"]),
page("webtoon-writing","format","VERTICAL STORY RHYTHM","Write the beat, then shape the scroll.","Connect episode, scene, beat, panel intent, reveal distance, and production notes.",["Episode and beat structure","Panel foundation","Vertical pacing intent"],format,[{title:"Reveal by distance",body:"A vertical canvas changes the timing between setup, pause, image, and reveal."},{title:"Story before production",body:"Panel breakdown inherits scene intent and canon instead of becoming a disconnected spreadsheet."}],["google-sheets","story-graph","revision"]),
page("manga-writing","format","PAGE-TURN INTELLIGENCE","Plan chapters, pages, panels, and reveals.","Model reading direction, page turns, panel intent, and story causality together.",["Page hierarchy foundation","Reading-direction intent","Shared canon"],format,[{title:"The page is a unit",body:"A page turn creates a narrative boundary that continuous-scroll formats do not share."},{title:"No false compliance claim",body:"The current system models planning concepts and does not yet claim print-ready manga layout."}],["webtoon-writing","formats","google-sheets"]),
page("game-writing","format","BRANCHING NARRATIVE MEMORY","Choices that remember what made them possible.","Connect dialogue nodes, prerequisites, world states, consequences, and alternate branches.",["Branch foundation","World-state intent","Dialogue-node architecture"],format,[{title:"Choice needs state",body:"A branch is meaningful when prerequisites and consequences remain queryable."},{title:"Alternates remain isolated",body:"Proposed paths should not silently rewrite the author-controlled main canon."}],["story-graph","worldbuilding","story-intelligence"]),
page("google","integration","GOOGLE WORKSPACE","Bring in the tools already holding your story.","Connect sign-in separately from optional Docs, Sheets, Drive, and Calendar permissions.",["Incremental consent foundation","Encrypted refresh tokens","Preview before mutation"],google,[{title:"Authentication is not access",body:"Signing in with Google does not automatically grant document, spreadsheet, Drive, or Calendar permissions."},{title:"PostgreSQL remains canonical",body:"Google files are user-selected sources and exports, never the product database."}],["google-docs","google-sheets","google-drive"]),
page("google-docs","integration","DOCUMENT IMPORT","Turn a manuscript into connected structure.","Select a document, preview detected headings and scenes, review unsupported formatting, then confirm.",["Heading detection design","Stable source-reference design","Confirmation boundary"],google,[{title:"Preview first",body:"The import architecture separates parse, normalize, validate, preview, and confirmed mutation."},{title:"Export deliberately",body:"New or updated Google Docs exports require explicit selection and retain export history in the design."}],["google","writing","google-drive"]),
page("google-sheets","integration","STRUCTURED IMPORT + EXPORT","Map rows into story records without surrendering canon.","Detect headers, map fields, normalize values, validate rows, preview changes, and retain row-level results.",["Mapping contracts","Row validation foundation","Audit trail design"],google,[{title:"Errors stay local",body:"One invalid row should not erase the valid work around it; failed rows remain retryable."},{title:"Matrices out, canon in",body:"Export planners and trackers while PostgreSQL remains the authoritative store."}],["google","webtoon-writing","translation"]),
page("google-drive","integration","USER-SELECTED FILES","Grant access to what the writer chooses.","Use selected-file references, permission-aware reconnect flows, and secure metadata storage.",["Incremental scope design","Reference recovery","Token isolation"],google,[{title:"Least access",body:"The integration requests capabilities incrementally rather than treating all Drive access as a login side effect."},{title:"Private references",body:"Refresh tokens remain encrypted server-side and private file URLs are never treated as public assets."}],["google","google-docs","security"]),
page("google-calendar","integration","DEADLINES WITH CONTEXT","Put writing time where the project can find it.","Create timezone-aware deadlines and writing sessions that link back to the authorized project.",["Timezone-aware design","Update and unlink flow","Project references"],google,[{title:"Writing milestones",body:"Chapter deadlines, editorial reviews, milestones, and recurring sessions are different event intents."},{title:"Reversible connection",body:"Calendar records can be updated or unlinked without deleting the underlying project plan."}],["google","planning","security"]),
page("languages","language","MULTILINGUAL BY DESIGN","Write in your language—not through English.","Keep interface language separate from manuscript language and its regional editorial conventions.",["English","Nederlands","Deutsch","Español","Português"],language,[{title:"Regional precision",body:"Projects support en-GB, en-US, nl-NL, nl-BE, de-DE, de-AT, de-CH, es-ES, es-MX, pt-PT, and pt-BR choices."},{title:"Interface is not manuscript",body:"Changing navigation language must never translate or mutate the writer’s prose."}],["languages/english","languages/dutch","translation"]),
...[["languages/english","English","en-GB · en-US"],["languages/dutch","Dutch","nl-NL · nl-BE"],["languages/german","German","de-DE · de-AT · de-CH"],["languages/spanish","Spanish","es-ES · es-MX"],["languages/portuguese","Portuguese","pt-PT · pt-BR"]].map(([slug,name,variants])=>page(slug,"language",`${name.toUpperCase()} EDITORIAL INTELLIGENCE`,`${name}, with its regional decisions intact.`,`Apply ${name} punctuation, spelling, register, and vocabulary conventions without changing story canon.`,[variants,"Voice preservation","Glossary decisions"],language,[{title:"A real editorial layer",body:"The target variant affects punctuation, address, spelling, and vocabulary—not merely translated interface copy."},{title:"Stable story identity",body:"Characters, objects, rules, and facts retain their identifiers across language versions."}],["languages","translation","writing"])),
page("pricing","commercial","FOUNDING ACCESS","Build with us while the story system grows.","Join founding access for product updates and an invitation when capacity opens. No unapproved price is shown.",["Individual path","Professional path","Studio path"],{label:"Choose your path",input:"Individual · Professional · Studio",output:"Founding-access request prepared; no payment or artificial urgency."},[{title:"Compare by work, not hype",body:"Plan configuration supports project, storage, AI, export, Google, collaboration, translation, and revision allowances."},{title:"Commercial honesty",body:"Checkout is not enabled and no price, discount, trial, or availability claim is presented as approved."}],["product","security","sign-up"]),
page("security","trust","PRIVATE BY DEFAULT","Your manuscript is not a marketing asset.","Sensitive reads and mutations are authorized on the server, with project scope and explicit integration boundaries.",["Server authorization","Encrypted Google tokens","Scoped AI context"],{label:"Inspect the boundary",input:"User → workspace membership → project",output:"Access allowed only after server-side membership and project checks."},[{title:"Tenant boundaries",body:"Workspace membership gates project reads, saves, searches, exports, and analysis routes."},{title:"Smallest useful context",body:"AI analysis is designed around selected scenes and retrieved canon rather than whole manuscripts by default."}],["privacy","google","story-intelligence"]),
page("privacy","trust","AUTHORSHIP + CONTROL","The writer decides what becomes canon.","AI suggestions remain separate records; project data is exportable; optional permissions are granted deliberately.",["No silent AI edits","Export foundation","Consent boundaries"],{label:"Review an AI decision",input:"Accept · edit · reject · alternate",output:"The original manuscript remains unchanged until an explicit author action."},[{title:"Provenance over magic",body:"Analysis records operation, model, prompt version, source IDs, explanation, and author decision."},{title:"Claims match implementation",body:"We do not claim completed deletion, billing, collaboration, or training-consent workflows that the product has not implemented."}],["security","story-intelligence","google"]),
];
export const marketingBySlug=new Map(marketingPages.map(p=>[p.slug,p]));
export const pricingConfig={mode:"founding-access" as const,billingPeriods:["monthly","annual"] as const,currencies:["EUR","USD","GBP"] as const,plans:[
{id:"individual",name:"Individual",description:"For one writer building connected stories",recommended:true,features:["Private projects","Rich-text drafting","Story bible","Markdown export","Google connection foundation"]},
{id:"professional",name:"Professional",description:"For writers managing deeper revision and translation",recommended:false,features:["Individual capabilities","Expanded analysis allowance","Translation workflows","Revision intelligence"]},
{id:"studio",name:"Studio",description:"For private creative teams",recommended:false,features:["Professional capabilities","Private collaboration architecture","Shared usage controls","Production exports"]}
]};
