export type PageKind="system"|"craft"|"intelligence"|"format"|"integration"|"language"|"trust"|"commercial";
export type MarketingPage={slug:string;kind:PageKind;eyebrow:string;title:string;description:string;proof:string[];interaction:{label:string;input:string;output:string};sections:{title:string;body:string}[];links:string[]};
const page=(slug:string,kind:PageKind,eyebrow:string,title:string,description:string,proof:string[],interaction:MarketingPage["interaction"],sections:MarketingPage["sections"],links:string[]):MarketingPage=>({slug,kind,eyebrow,title,description,proof,interaction,sections,links});
const check={label:"See what Morrow remembers",input:"Lena hands Tomas the silver key in Chapter 5.",output:"A gentle note points to Chapter 8, where Lena still carries it."};
const plan={label:"Move the story forward",input:"Drag “The visitor arrives” before “The second restoration.”",output:"The reveal now lands earlier. Two later scene notes move with it."};
const formatDemo={label:"Change the shape of the workspace",input:"Novel → screenplay → webtoon",output:"Chapters become sluglines or panels while the characters and story details stay close."};
const languageDemo={label:"Hear the difference",input:"English → German → Spanish",output:"Punctuation, address, preferred terms, and character voice adapt together."};
const googleDemo={label:"Bring in what you already have",input:"The Museum of Lost Hours · Google Doc",output:"Preview: 8 chapters, 19 scenes, 7 characters. Nothing changes until you confirm."};

export const marketingPages:MarketingPage[]=[
page("product","system","THE WHOLE STORY, CLOSE BY","Write freely. Your story remembers the rest.","Morrow brings your draft, plans, characters, and revisions into one beautiful place that stays easy to use.",["Write without losing details","Find what matters quickly","Stay in control"],check,[{title:"Less searching. More writing.",body:"Open the right chapter, find a character note, or revisit an earlier promise without digging through scattered files."},{title:"Helpful, never intrusive",body:"Morrow waits quietly while you write and brings forward a detail only when it can genuinely help."}],["writing","planning","privacy"]),
page("writing","craft","A CALMER WRITING ROOM","A spacious place to stay with the words.","Write chapters and scenes with the notes you need nearby—and everything else out of sight.",["Beautiful manuscript editor","Reliable autosave","Version history"],{label:"Open a scene",input:"Chapter 8 · The conservation room",output:"Your scene, its purpose, and the relevant character notes appear together."},[{title:"The manuscript comes first",body:"Focus mode clears the room. Chapter and scene navigation return the moment you need them."},{title:"Every draft is safer",body:"Morrow saves as you work and keeps earlier versions available when you want to look back."}],["planning","revision","formats"]),
page("planning","craft","PLAN WITHOUT LOSING THE SPARK","Give the story shape. Keep room for surprise.","Move from a loose premise to chapters, scenes, and turning points without making the work feel mechanical.",["Flexible outline","Scene purpose","Series planning"],plan,[{title:"See the middle more clearly",body:"Follow each character’s movement through the story and notice where momentum fades."},{title:"Change your mind freely",body:"Reorder scenes and keep their notes, people, and open questions attached."}],["characters","timeline","writing"]),
page("story-intelligence","intelligence","QUIETLY PERCEPTIVE","The kind of help that reads the room.","Morrow notices forgotten details, thin motivations, repeated explanations, and promises waiting for an ending.",["Specific passages","Clear reasons","Your decision"],check,[{title:"No vague advice",body:"Every suggestion opens the exact passage and the earlier moment that prompted it."},{title:"You choose what changes",body:"Add it to your revision plan, dismiss it, mark it intentional, or compare another approach."}],["continuity","revision","writing"]),
page("story-graph","system","FOLLOW THE THREAD","See how one change travels through the story.","A simple visual view shows which scenes, characters, and promises may need another look—without asking you to learn a technical system.",["Story at a glance","Change preview","Alternate paths"],check,[{title:"Start from the writing",body:"Open a scene and follow only the details connected to the choice you are making now."},{title:"Preview before changing",body:"See which later moments may be affected before committing to a major rewrite."}],["continuity","timeline","revision"]),
page("characters","craft","PEOPLE WHO CHANGE","Remember who your characters are becoming.","Keep goals, secrets, relationships, voice, and the latest emotional state close to the scenes that shape them.",["Goals and fears","Relationships","Current state"],{label:"Open Lena’s current state",input:"After the second restoration",output:"Determined · withholding · distrustful of Tomas · still carrying the key"},[{title:"More than a profile",body:"A character page shows not only who someone is, but what has just changed for them."},{title:"Know what they know",body:"Check whether a line of dialogue matches what the character has actually learned so far."}],["relationships","continuity","writing"]),
page("relationships","intelligence","RELATIONSHIPS IN MOTION","Follow trust, tension, and everything unsaid.","See the scenes that move two people closer, pull them apart, or change who holds the power.",["Changing trust","Hidden tension","Scene history"],{label:"Follow Lena and Tomas",input:"Chapter 4: guarded allies",output:"Chapter 8: Lena lies about the key. Trust falls; dependence rises."},[{title:"The turn has a reason",body:"Each shift opens the scene, decision, or revelation that caused it."},{title:"Two sides of the same bond",body:"What Lena feels about Tomas can be different from what Tomas believes about Lena."}],["characters","revision","timeline"]),
page("worldbuilding","craft","A WORLD THAT HOLDS TOGETHER","Keep places, objects, groups, and rules easy to find.","Build a story world rich enough to surprise the reader and consistent enough to feel real.",["Places and objects","World rules","Research notes"],{label:"Follow the silver key",input:"Hidden in the blue frame",output:"Found by Lena · moved to conservation room · promised to Tomas"},[{title:"Details stay useful",body:"A world note can appear beside the scene where it matters, rather than living in a forgotten document."},{title:"Exceptions are part of the world",body:"When a rule bends, record why so a deliberate mystery never looks like an accident."}],["timeline","characters","planning"]),
page("timeline","system","WHEN EVERYTHING HAPPENS","Keep story time and reveal time clear.","See when an event happened, when a character learned about it, and when the reader discovered the truth.",["Story timeline","Character discoveries","Reader reveals"],{label:"Compare two moments",input:"Portrait restored · 14 October",output:"Lena notices the change that night; the reader learns why in Chapter 11."},[{title:"Untangle complex chronology",body:"Move between flashbacks, parallel plots, and long time jumps without losing the order underneath."},{title:"Catch impossible timing",body:"Morrow can point out travel, possession, or knowledge that happens too soon."}],["continuity","planning","revision"]),
page("continuity","intelligence","STAY CONSISTENT WITHOUT SLOWING DOWN","Catch the small details before they become big rewrites.","Morrow checks names, objects, knowledge, time, relationships, and open promises while keeping the manuscript at the center.",["Exact earlier passage","Simple explanation","Suggested next steps"],check,[{title:"A question, not a verdict",body:"A note explains what may disagree and lets you decide whether it is a mistake, a mystery, or intentional misdirection."},{title:"Fix it where it belongs",body:"Open both scenes side by side and choose the smallest change that keeps your intention intact."}],["story-intelligence","timeline","revision"]),
page("revision","intelligence","A REVISION PLAN YOU CAN FOLLOW","Turn a difficult rewrite into clear, scene-sized work.","Move from pacing, character, exposition, and payoff findings to exact passages and practical next actions.",["Exact scenes","Prioritized plan","Before and after"],{label:"Open a pacing finding",input:"Chapter 6 slows after the reveal",output:"Three repeated explanations are highlighted; Lena’s reaction can move forward."},[{title:"Know where to begin",body:"Group findings by the change they create, not by a wall of generic feedback."},{title:"See the difference",body:"Compare alternatives beside the original and keep the final choice yours."}],["writing","continuity","story-intelligence"]),
page("translation","language","THE SAME CHARACTER, IN EVERY LANGUAGE","Adapt the writing without losing the person inside it.","Keep names, facts, preferred terms, dialogue style, and character voice consistent across translations.",["Voice notes","Preferred terms","Regional conventions"],languageDemo,[{title:"More than word replacement",body:"Punctuation, formality, idiom, and rhythm change with the language and region."},{title:"Shared story details",body:"A change to a name or fact can be reviewed in every translated passage that uses it."}],["languages","revision","google-sheets"]),
page("formats","format","EVERY STORY HAS ITS OWN SHAPE","A workspace that feels right for the way you write.","Move between novels, screenplays, television, webtoons, manga, comics, and game narrative.",["The right structure","Shared characters","One creative home"],formatDemo,[{title:"The interface adapts",body:"Novelists see chapters and prose. Screenwriters see scenes and dialogue. Webtoon creators see beats and panels."},{title:"Your story still feels like one story",body:"Characters, places, and essential details remain available across formats."}],["novel-writing","screenwriting","webtoon-writing"]),
...[["novel-writing","NOVEL WRITING","A long-form home for chapters, scenes, and prose.","Chapters · scenes · POV · word goals"],["screenwriting","SCREENWRITING","Keep every scene purposeful and playable.","Sluglines · action · cues · dialogue"],["tv-writing","TELEVISION WRITING","Hold the episode and the season in mind.","Episodes · acts · storylines · season arcs"],["webtoon-writing","WEBTOON WRITING","Shape the beat, the panel, and the scroll.","Episodes · beats · panels · reveals"],["manga-writing","MANGA WRITING","Plan pages, panels, and page-turn moments.","Chapters · pages · panels · page turns"],["game-writing","GAME NARRATIVE","Write choices that remember what came before.","Quests · choices · dialogue · world states"]].map(([slug,eyebrow,title,detail])=>page(slug,"format",eyebrow,title,`Morrow adapts to ${detail.toLowerCase()} while keeping your characters and story details close.`,[...detail.split(" · ").slice(0,3)],formatDemo,[{title:"Made for the format",body:`The workspace uses ${detail.toLowerCase()} rather than forcing every story into the same outline.`},{title:"Your story stays connected",body:"Changes to characters, places, and important facts remain visible wherever they matter."}],["formats","writing","planning"])),
page("google","integration","GOOGLE WORKSPACE","Bring the work you already have.","Import a manuscript from Docs, bring characters or a timeline from Sheets, and keep writing without starting over.",["Preview first","Original files stay put","Google stays optional"],googleDemo,[{title:"Four simple steps",body:"Connect, preview, confirm, and continue writing. Morrow explains issues in plain language."},{title:"Useful both ways",body:"Bring work in from Google or send a chapter plan, timeline, or revision list back out."}],["google-docs","google-sheets","google-drive"]),
page("google-docs","integration","GOOGLE DOCS","Bring in a manuscript without flattening it.","Preview chapters, scenes, paragraphs, and formatting before anything joins your Morrow project.",["Chapter preview","Formatting review","Confirmed import"],googleDemo,[{title:"See what Morrow found",body:"Review chapter headings, scene breaks, and anything that needs attention before importing."},{title:"Send work back out",body:"Create a new Google Doc for a manuscript or update an existing export after confirmation."}],["google","writing","google-drive"]),
page("google-sheets","integration","GOOGLE SHEETS","Bring plans and trackers into the story.","Match familiar columns for characters, timelines, scenes, panels, translations, or revision tasks.",["Friendly column matching","Row-by-row fixes","Useful exports"],{label:"Preview a character sheet",input:"Name · role · goal · secret",output:"24 rows ready · 2 names need review · fix them before importing"},[{title:"Fix issues in place",body:"Missing names and unclear references are highlighted with plain explanations."},{title:"Keep Sheets useful",body:"Export a story outline, scene tracker, webtoon script, revision plan, or translation tracker whenever you need one."}],["google","planning","translation"]),
page("google-drive","integration","GOOGLE DRIVE","Keep research and source files nearby.","Choose the files or folder you want Morrow to use. Reconnect a moved file without rebuilding the project.",["You choose the files","Research close by","Easy reconnect"],googleDemo,[{title:"Only what you select",body:"Drive access is optional and stays separate from signing in."},{title:"A link back to the source",body:"Research notes remember which selected file they came from."}],["google","google-docs","privacy"]),
page("google-calendar","integration","GOOGLE CALENDAR","Make room for the work.","Add writing sessions, chapter deadlines, editorial reviews, and milestones to the calendar you already use.",["Writing sessions","Story deadlines","Project links"],{label:"Add a deadline",input:"Finish Chapter 8 · Friday 17:00",output:"Preview the event, timezone, and project link before adding it."},[{title:"Plans with a place in the week",body:"Turn a revision task or chapter goal into a calendar moment without copying details by hand."},{title:"Change or unlink anytime",body:"Updating the writing plan does not trap the project inside Calendar."}],["google","planning","revision"]),
page("languages","language","FIVE LANGUAGES. MANY VOICES.","Write for the language your story belongs in.","Morrow supports English, Dutch, German, Spanish, and Portuguese with regional writing choices.",["Dialogue conventions","Regional spelling","Character voice"],languageDemo,[{title:"The interface is separate",body:"Changing menus never translates or alters the manuscript."},{title:"Choose the right region",body:"Projects can distinguish variants such as en-GB, nl-BE, de-CH, es-MX, and pt-BR."}],["languages/english","languages/dutch","translation"]),
...[["languages/english","English","en-US · en-GB"],["languages/dutch","Dutch","nl-NL · nl-BE"],["languages/german","German","de-DE · de-AT · de-CH"],["languages/spanish","Spanish","es-ES · es-MX"],["languages/portuguese","Portuguese","pt-PT · pt-BR"]].map(([slug,name,variants])=>page(slug,"language",`${name.toUpperCase()} WRITING`,`${name}, with the right rhythm and conventions.`,`Review punctuation, spelling, register, preferred terms, and character voice for ${variants}.`,[variants,"Dialogue style","Voice consistency"],languageDemo,[{title:"Writing choices, not marketing translation",body:"Morrow focuses on the details that make fiction feel native to its target readers."},{title:"One story underneath",body:"Names, events, relationships, and important objects remain consistent across every language version."}],["languages","translation","writing"])),
page("pricing","commercial","SIMPLE PRICING","Choose the support your story needs.","Start free, then choose a plan when you want more projects, deeper reviews, translation, or a shared studio.",["Start free","Cancel anytime","Export anytime"],{label:"Choose your plan",input:"Writer · Professional · Studio",output:"Compare projects, monthly review allowance, languages, and collaboration in plain language."},[{title:"Pay for outcomes",body:"Plans grow from finishing one story to managing deeper multilingual work and private creative teams."},{title:"No lock-in",body:"Your writing remains exportable. A paid plan adds room and assistance, not ownership over your work."}],["product","privacy","sign-up"]),
page("security","trust","A SAFE PLACE TO WRITE","Private by default, from the first page.","Morrow protects project access on the server and keeps optional connected accounts separate.",["Private projects","Protected connections","Exportable work"],{label:"Open a private project",input:"Writer → invited workspace → selected story",output:"Only people with permission can open or change the project."},[{title:"Your project is not public",body:"There are no public profiles, reader feeds, or marketplace pages."},{title:"Connections remain optional",body:"Signing in does not automatically grant access to Google Docs, Sheets, Drive, or Calendar."}],["privacy","google","product"]),
page("privacy","trust","YOUR STORY STAYS YOURS","Clear choices. No quiet surprises.","AI suggestions never overwrite your writing, Google access is optional, and project data can be exported.",["No silent changes","Optional AI help","Export anytime"],{label:"Review a suggestion",input:"Keep · edit · dismiss · mark intentional",output:"The manuscript stays unchanged until you make a clear choice."},[{title:"You remain the author",body:"Morrow offers observations and alternatives. It does not make hidden edits to your manuscript."},{title:"Permission should feel understandable",body:"Connected services explain what they need at the moment you choose to use them."}],["security","google","writing"]),
];
export const marketingBySlug=new Map(marketingPages.map(item=>[item.slug,item]));
export const pricingConfig={billingPeriods:["monthly","annual"] as const,currencies:{EUR:"€",USD:"$",GBP:"£"} as const,plans:[
{id:"writer",name:"Writer",description:"For finishing your own stories",monthly:{EUR:12,USD:14,GBP:11},recommended:false,features:["3 active stories","20 thoughtful reviews each month","Google Docs and Sheets","Markdown and DOCX export"]},
{id:"professional",name:"Professional",description:"For deeper projects and multiple languages",monthly:{EUR:24,USD:27,GBP:22},recommended:true,features:["Unlimited active stories","80 thoughtful reviews each month","Translation workspace","Advanced revision planning"]},
{id:"studio",name:"Studio",description:"For collaborative story teams and publishers",monthly:{EUR:59,USD:65,GBP:52},recommended:false,features:["5 private collaborators","Shared story library","Team review workflow","Priority support"]},
]};
