import type { Prisma } from "@/generated/prisma";
import type { CanvasState, EntityType, StoryEntity } from "./types";
import { createCanvasState } from "./fixtures";
import { normalizeManuscript } from "./manuscript";

export const workspaceInclude = {
  parts: { where: { deletedAt: null }, orderBy: { position: "asc" as const } },
  chapters: { where: { deletedAt: null }, orderBy: { position: "asc" as const }, include: { scenes: { where: { deletedAt: null }, orderBy: { position: "asc" as const } } } },
  canonUniverse: { include: { entities: { where: { deletedAt: null }, include: { mentions: { where: { active: true }, select: { sceneId: true } } } } } },
} satisfies Prisma.SeriesInclude;
export type WorkspaceRecord = Prisma.SeriesGetPayload<{ include: typeof workspaceInclude }>;

const type = (value: string): EntityType => value === "CHARACTER" ? "person" : value === "PLACE" ? "place" : value === "OBJECT" ? "object" : value === "FACTION" ? "faction" : value === "QUESTION" ? "question" : "event";
export function serializeWorkspace(project: WorkspaceRecord, sync?: CanvasState["sync"]): CanvasState {
  const seed = createCanvasState();
  const scenes = project.chapters.flatMap((chapter) => chapter.scenes.map((scene) => ({ id: scene.id, chapterId: scene.chapterId, title: scene.title, manuscriptJson: normalizeManuscript(scene.manuscriptJson, scene.manuscriptText, scene.id), manuscriptText: scene.manuscriptText, content: scene.manuscriptText, location: "", people: [], objects: [], summary: scene.purpose, order: chapter.position * 1000 + scene.position, position: scene.position, status: (scene.status === "ARCHIVED" ? "archived" : "active") as "active" | "archived", pointOfViewEntityId: scene.pointOfViewEntityId ?? undefined, locationEntityId: scene.locationEntityId ?? undefined, wordCount: scene.wordCount, lastEditedAt: scene.lastEditedAt.toISOString(), revision: scene.revision })));
  const entities: StoryEntity[] = (project.canonUniverse?.entities ?? []).map((entity) => { const metadata = (entity.metadata ?? {}) as Record<string, unknown>; return { id: entity.id, name: entity.name, type: type(entity.entityType), aliases: Array.isArray(metadata.aliases) ? metadata.aliases.map(String) : [], role: typeof metadata.role === "string" ? metadata.role : undefined, pronouns: typeof metadata.pronouns === "string" ? metadata.pronouns : undefined, description: typeof metadata.description === "string" ? metadata.description : undefined, currentLocation: typeof metadata.location === "string" ? metadata.location : undefined, currentHolder: typeof metadata.holder === "string" ? metadata.holder : undefined, currentOwner: typeof metadata.owner === "string" ? metadata.owner : undefined, atmosphere: typeof metadata.atmosphere === "string" ? metadata.atmosphere : undefined, state: typeof metadata.state === "string" ? metadata.state : undefined, appearances: [...new Set(entity.mentions.map((mention) => mention.sceneId))], sourceCount: entity.mentions.length, status: "active" }; });
  return { ...seed, version: 3, project: { id: project.id, title: project.title, type: project.projectType === "NARRATIVE_DESIGN" ? "GAME_NARRATIVE" : project.projectType, premise: project.premise, language: project.language, parts: project.parts.map((part) => ({ id: part.id, projectId: project.id, title: part.title, position: part.position, chapterIds: project.chapters.filter((chapter) => chapter.partId === part.id).map((chapter) => chapter.id), status: part.status === "ARCHIVED" ? "archived" : "active" })), chapters: project.chapters.map((chapter) => ({ id: chapter.id, projectId: project.id, partId: chapter.partId ?? undefined, title: chapter.title, position: chapter.position, summary: chapter.summary, status: chapter.status === "ARCHIVED" ? "archived" : "active", sceneIds: chapter.scenes.map((scene) => scene.id), createdAt: chapter.createdAt.toISOString(), updatedAt: chapter.updatedAt.toISOString() })), scenes, createdAt: project.createdAt.toISOString(), updatedAt: project.updatedAt.toISOString() }, projectTitle: project.title, scenes, entities, currentSceneId: scenes[0]?.id ?? "", selectedEntityId: entities.find((entity) => entity.type === "object")?.id ?? entities[0]?.id, sync: sync ?? { status: "not-connected", grantedServices: [] }, dataMode: "production" };
}
