import { z } from "zod"; import { auth } from "@/auth"; import { prisma } from "@/lib/prisma"; import { requireProjectAccess } from "@/server/authorization";
const create = z.discriminatedUnion("operation", [z.object({ operation: z.literal("create-part"), title: z.string().trim().min(1).max(240).default("Untitled part"), position: z.number().int().nonnegative().optional() }), z.object({ operation: z.literal("create-chapter"), title: z.string().trim().min(1).max(240).default("Untitled chapter"), partId: z.string().optional(), position: z.number().int().nonnegative().optional() }), z.object({ operation: z.literal("create-scene"), title: z.string().trim().min(1).max(240).default("Untitled scene"), chapterId: z.string(), position: z.number().int().nonnegative().optional() })]);
const command = z.object({ type: z.enum(["move-chapter", "duplicate-chapter", "archive-chapter", "restore-chapter", "delete-chapter", "rename-chapter", "move-scene", "duplicate-scene", "archive-scene", "restore-scene", "delete-scene", "rename-scene"]), id: z.string(), direction: z.enum(["before", "after", "earlier", "later"]).optional(), targetId: z.string().optional(), value: z.string().max(240).optional(), position: z.number().int().nonnegative().optional() });
async function access(projectId: string) { const session = await auth(); if (!session?.user?.id) return null; await requireProjectAccess(session.user.id, projectId, ["OWNER", "WRITER", "EDITOR"]); return session.user.id; }
export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { if (!await access(projectId)) return Response.json({ error: "Unauthorized" }, { status: 401 }); const parsed = create.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Check the structure details", details: parsed.error.flatten() }, { status: 400 }); const value = parsed.data;
  if (value.operation === "create-part") { const count = await prisma.storyPart.count({ where: { seriesId: projectId, deletedAt: null } }); const record = await prisma.storyPart.create({ data: { seriesId: projectId, title: value.title, position: value.position ?? count } }); return Response.json({ ...record, projectId, chapterIds: [], status: "active" }, { status: 201 }); }
  if (value.operation === "create-chapter") { if (value.partId && !await prisma.storyPart.findFirst({ where: { id: value.partId, seriesId: projectId, deletedAt: null } })) return Response.json({ error: "Part is outside this project" }, { status: 400 }); const count = await prisma.chapter.count({ where: { seriesId: projectId, deletedAt: null } }); const record = await prisma.chapter.create({ data: { seriesId: projectId, title: value.title, number: count + 1, position: value.position ?? count, partId: value.partId } }); return Response.json({ ...record, projectId, sceneIds: [], status: "active", createdAt: record.createdAt.toISOString(), updatedAt: record.updatedAt.toISOString() }, { status: 201 }); }
  const chapter = await prisma.chapter.findFirst({ where: { id: value.chapterId, seriesId: projectId, deletedAt: null } }); if (!chapter) return Response.json({ error: "Chapter is outside this project" }, { status: 400 }); const count = await prisma.scene.count({ where: { chapterId: chapter.id, deletedAt: null } }); const record = await prisma.scene.create({ data: { chapterId: chapter.id, title: value.title, position: value.position ?? count } }); return Response.json({ id: record.id, chapterId: record.chapterId, title: record.title, content: "", location: "", people: [], objects: [], summary: "", order: chapter.position * 1000 + record.position, position: record.position, status: "active", wordCount: 0, lastEditedAt: record.lastEditedAt.toISOString(), revision: 0 }, { status: 201 });
  } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Forbidden" }, { status: 403 }); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; try { if (!await access(projectId)) return Response.json({ error: "Unauthorized" }, { status: 401 }); const parsed = command.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Check the structure command" }, { status: 400 }); const value = parsed.data; const chapter = await prisma.chapter.findFirst({ where: { id: value.id, seriesId: projectId } }); const scene = chapter ? null : await prisma.scene.findFirst({ where: { id: value.id, chapter: { seriesId: projectId } } });
  if (value.type === "rename-chapter" && chapter) await prisma.chapter.update({ where: { id: chapter.id }, data: { title: value.value?.trim() || "Untitled chapter" } });
  else if (value.type === "rename-scene" && scene) await prisma.scene.update({ where: { id: scene.id }, data: { title: value.value?.trim() || "Untitled scene" } });
  else if ((value.type === "archive-chapter" || value.type === "restore-chapter") && chapter) await prisma.chapter.update({ where: { id: chapter.id }, data: { status: value.type === "archive-chapter" ? "ARCHIVED" : "ACTIVE", deletedAt: null } });
  else if ((value.type === "archive-scene" || value.type === "restore-scene") && scene) await prisma.scene.update({ where: { id: scene.id }, data: { status: value.type === "archive-scene" ? "ARCHIVED" : "ACTIVE", deletedAt: null } });
  else if (value.type === "delete-chapter" && chapter) await prisma.chapter.update({ where: { id: chapter.id }, data: { deletedAt: new Date() } });
  else if (value.type === "delete-scene" && scene) await prisma.scene.update({ where: { id: scene.id }, data: { deletedAt: new Date() } });
  else if (value.type === "duplicate-chapter" && chapter) { const source = await prisma.chapter.findUnique({ where: { id: chapter.id }, include: { scenes: { where: { deletedAt: null }, orderBy: { position: "asc" } } } }); if (source) await prisma.$transaction(async (tx) => { const count = await tx.chapter.count({ where: { seriesId: projectId, deletedAt: null } }); const copy = await tx.chapter.create({ data: { seriesId: projectId, title: `${source.title} copy`, number: count + 1, position: count, partId: source.partId, summary: source.summary } }); for (const item of source.scenes) await tx.scene.create({ data: { chapterId: copy.id, title: item.title, position: item.position, manuscriptJson: JSON.parse(JSON.stringify(item.manuscriptJson)), manuscriptText: item.manuscriptText, wordCount: item.wordCount, purpose: item.purpose } }); }); }
  else if (value.type === "duplicate-scene" && scene) { const count = await prisma.scene.count({ where: { chapterId: scene.chapterId, deletedAt: null } }); await prisma.scene.create({ data: { chapterId: scene.chapterId, title: `${scene.title} copy`, position: count, manuscriptJson: JSON.parse(JSON.stringify(scene.manuscriptJson)), manuscriptText: scene.manuscriptText, wordCount: scene.wordCount, purpose: scene.purpose } }); }
  else if (value.type === "move-scene" && scene) { const targetChapterId = value.targetId ?? scene.chapterId; if (!await prisma.chapter.findFirst({ where: { id: targetChapterId, seriesId: projectId, deletedAt: null } })) return Response.json({ error: "Target chapter is outside this project" }, { status: 400 }); const targetPosition = value.position ?? scene.position; await prisma.$transaction(async (tx) => { await tx.scene.update({ where: { id: scene.id }, data: { position: -1 } }); const siblings = await tx.scene.findMany({ where: { chapterId: targetChapterId, deletedAt: null, id: { not: scene.id } }, orderBy: { position: "asc" } }); for (let index = 0; index < siblings.length; index++) await tx.scene.update({ where: { id: siblings[index].id }, data: { position: index >= targetPosition ? index + 1 : index } }); await tx.scene.update({ where: { id: scene.id }, data: { chapterId: targetChapterId, position: Math.min(targetPosition, siblings.length) } }); }); }
  else if (value.type === "move-chapter" && chapter) { const target = value.position ?? Math.max(0, chapter.position + (value.direction === "earlier" ? -1 : 1)); await prisma.$transaction(async (tx) => { await tx.chapter.update({ where: { id: chapter.id }, data: { position: -1 } }); const siblings = await tx.chapter.findMany({ where: { seriesId: projectId, deletedAt: null, id: { not: chapter.id } }, orderBy: { position: "asc" } }); for (let index = 0; index < siblings.length; index++) await tx.chapter.update({ where: { id: siblings[index].id }, data: { position: index >= target ? index + 1 : index } }); await tx.chapter.update({ where: { id: chapter.id }, data: { position: Math.min(target, siblings.length) } }); }); }
  return Response.json({ ok: true, projectId }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Forbidden" }, { status: 403 }); } }
