ALTER TYPE "CanonStatus" RENAME VALUE 'APPROVED' TO 'CANON';
ALTER TYPE "CanonStatus" ADD VALUE 'PROPOSED';
ALTER TYPE "CanonStatus" ADD VALUE 'ALTERNATE';
ALTER TYPE "CanonStatus" ADD VALUE 'ARCHIVED';
CREATE TYPE "ProjectType" AS ENUM ('NOVEL','SCREENPLAY','WEBTOON','SERIAL_FICTION','COMIC','NARRATIVE_DESIGN');
CREATE TYPE "PointOfView" AS ENUM ('FIRST_PERSON','SECOND_PERSON','THIRD_LIMITED','THIRD_OMNISCIENT','MULTIPLE');
CREATE TYPE "NarrativeTense" AS ENUM ('PAST','PRESENT','MIXED');
CREATE TYPE "AiDecision" AS ENUM ('PENDING','ACCEPTED','REJECTED');
ALTER TABLE "Profile" ADD COLUMN "interfaceLocale" TEXT NOT NULL DEFAULT 'en';
ALTER TABLE "Series" ADD COLUMN "projectType" "ProjectType" NOT NULL DEFAULT 'NOVEL', ADD COLUMN "regionalVariant" TEXT NOT NULL DEFAULT 'en-US', ADD COLUMN "pointOfView" "PointOfView" NOT NULL DEFAULT 'THIRD_LIMITED', ADD COLUMN "narrativeTense" "NarrativeTense" NOT NULL DEFAULT 'PAST', ADD COLUMN "premise" TEXT NOT NULL DEFAULT '';
CREATE TABLE "Chapter" ("id" TEXT PRIMARY KEY,"seriesId" TEXT NOT NULL REFERENCES "Series"("id") ON DELETE CASCADE,"title" TEXT NOT NULL,"number" INTEGER NOT NULL,"kind" TEXT NOT NULL DEFAULT 'CHAPTER',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"deletedAt" TIMESTAMP(3),UNIQUE("seriesId","number"));
CREATE TABLE "Scene" ("id" TEXT PRIMARY KEY,"chapterId" TEXT NOT NULL REFERENCES "Chapter"("id") ON DELETE CASCADE,"title" TEXT NOT NULL,"position" INTEGER NOT NULL,"purpose" TEXT NOT NULL DEFAULT '',"conflict" TEXT NOT NULL DEFAULT '',"stakes" TEXT NOT NULL DEFAULT '',"outcome" TEXT NOT NULL DEFAULT '',"manuscriptJson" JSONB NOT NULL DEFAULT '{"type":"doc","content":[{"type":"paragraph"}]}',"manuscriptText" TEXT NOT NULL DEFAULT '',"revision" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"deletedAt" TIMESTAMP(3),UNIQUE("chapterId","position"));
CREATE TABLE "StoryBeat" ("id" TEXT PRIMARY KEY,"sceneId" TEXT NOT NULL REFERENCES "Scene"("id") ON DELETE CASCADE,"position" INTEGER NOT NULL,"type" TEXT NOT NULL,"summary" TEXT NOT NULL,"canonStatus" "CanonStatus" NOT NULL DEFAULT 'DRAFT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,UNIQUE("sceneId","position"));
CREATE TABLE "ManuscriptVersion" ("id" TEXT PRIMARY KEY,"sceneId" TEXT NOT NULL REFERENCES "Scene"("id") ON DELETE CASCADE,"userId" TEXT NOT NULL,"revision" INTEGER NOT NULL,"manuscriptJson" JSONB NOT NULL,"manuscriptText" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("sceneId","revision"));
CREATE TABLE "AiSuggestion" ("id" TEXT PRIMARY KEY,"seriesId" TEXT NOT NULL REFERENCES "Series"("id") ON DELETE CASCADE,"sceneId" TEXT NOT NULL REFERENCES "Scene"("id") ON DELETE CASCADE,"requestedById" TEXT NOT NULL,"operation" TEXT NOT NULL,"requestedLocale" TEXT NOT NULL,"contextRecordIds" TEXT[],"result" JSONB NOT NULL,"explanation" TEXT NOT NULL,"model" TEXT NOT NULL,"promptVersion" TEXT NOT NULL,"decision" "AiDecision" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"decidedAt" TIMESTAMP(3));
CREATE INDEX "Chapter_seriesId_deletedAt_idx" ON "Chapter"("seriesId","deletedAt");
CREATE INDEX "Scene_chapterId_deletedAt_idx" ON "Scene"("chapterId","deletedAt");
CREATE INDEX "ManuscriptVersion_userId_idx" ON "ManuscriptVersion"("userId");
CREATE INDEX "AiSuggestion_seriesId_sceneId_idx" ON "AiSuggestion"("seriesId","sceneId");
